"""
Out-of-distribution (OOD) evaluation for an already-trained case, per the
advisor's request: "the test data are sampled from the same distribution
as the training data ... include OOD predictions, for example different
material ranges and loading magnitudes."

This does NOT retrain anything -- it loads an existing checkpoint
(model_best.pt or model_final.pt from a normal training run) and runs it,
unchanged, on two test sets side by side:
  1. the case's own in-distribution NPZ (same distribution as training),
  2. a separate OOD NPZ generated by data_generate_B{1,2}.py with
     --E_mean/--E_std/--ty_mean (B1) or --p_mean (B2) etc. overridden away
     from the in-distribution defaults (see those scripts' main()).

Usage (B1 example):
  python -m omar_pfem.evaluate_ood \
      --geometry B1 --material neo_hookean \
      --checkpoint /path/to/B1_neo_hookean/model_best.pt \
      --id_path /path/to/B1_neo_hookean/in_distribution.npz \
      --ood_path /path/to/B1_neo_hookean_ood/ood.npz \
      --ntest 200 --out_json ood_report_B1_neo_hookean.json

Both NPZ files must be in the same converted format the training scripts
already consume (convert_B1_quad.py / convert_B2_quad.py output) -- the
OOD one just comes from a differently-parameterized data_generate_B{1,2}.py
run over the same mesh/material/geometry.
"""
import argparse
import json
import torch

from omar_pfem.model_dict import get_model


def build_model(args, device):
    model = get_model(args).Model(
        space_dim=2,
        n_layers=args.n_layers,
        n_hidden=args.n_hidden,
        dropout=args.dropout,
        n_head=args.n_heads,
        Time_Input=False,
        mlp_ratio=args.mlp_ratio,
        fun_dim=args.fun_dim,
        out_dim=2,
        slice_num=args.slice_num,
        ref=args.ref,
        unified_pos=args.unified_pos,
    ).to(device)
    return model


def main():
    parser = argparse.ArgumentParser(
        "OOD evaluation: load a trained checkpoint, evaluate it (no retraining) "
        "on both its in-distribution test set and a separately-generated OOD test set."
    )
    parser.add_argument("--geometry", type=str, required=True, choices=["B1", "B2"])
    parser.add_argument("--material", type=str, required=True,
                         choices=["neo_hookean", "mooney_rivlin", "arruda_boyce"])
    parser.add_argument("--checkpoint", type=str, required=True,
                         help="Path to model_best.pt or model_final.pt from a normal training run")
    parser.add_argument("--id_path", type=str, required=True,
                         help="In-distribution NPZ (the case's own converted dataset)")
    parser.add_argument("--ood_path", type=str, required=True,
                         help="Out-of-distribution NPZ (converted output of a "
                              "data_generate_B{1,2}.py run with shifted E/nu/load parameters)")
    parser.add_argument("--ntest", type=int, default=200,
                         help="Number of samples to evaluate from each of id_path/ood_path "
                              "(uses the LAST ntest samples in each file as the test split, "
                              "matching train_B1.py/train_B2.py's own ntrain/ntest convention)")

    # Architecture -- must match the checkpoint's training run exactly (Table 1 defaults).
    parser.add_argument("--model", type=str, default="Transolver_Irregular_Mesh")
    parser.add_argument("--n_hidden", type=int, default=256)
    parser.add_argument("--n_layers", type=int, default=4)
    parser.add_argument("--n_heads", type=int, default=8)
    parser.add_argument("--mlp_ratio", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--unified_pos", type=int, default=0)
    parser.add_argument("--ref", type=int, default=16)
    parser.add_argument("--slice_num", type=int, default=128)
    parser.add_argument("--fun_dim", type=int, default=4)

    # Physics/BC settings -- must match training (defaults match train_B1.py/train_B2.py's own).
    parser.add_argument("--mode", type=str, default="plane_strain", choices=["plane_stress", "plane_strain"])
    parser.add_argument("--use_soft_dirichlet", type=int, default=1)
    parser.add_argument("--Lx", type=float, default=1.0)
    parser.add_argument("--Ly", type=float, default=1.0)
    parser.add_argument("--R_out", type=float, default=2.0)

    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--out_json", type=str, default=None,
                         help="If set, write the full report to this path in addition to stdout")

    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    dtype = torch.float32

    if args.geometry == "B1":
        from omar_pfem.train_B1 import (
            evaluate_dataset_hyperelastic_Q4,
            load_fem_dataset_Q4_with_materials_and_random_force,
        )
    else:
        from omar_pfem.train_B2 import (
            evaluate_dataset_hyperelastic_Q4,
            load_fem_dataset_Q4_with_materials_and_random_force,
        )

    model = build_model(args, device)
    state_dict = torch.load(args.checkpoint, map_location=device)
    model.load_state_dict(state_dict)
    model.eval()
    print(f"Loaded checkpoint: {args.checkpoint}")

    _, id_test = load_fem_dataset_Q4_with_materials_and_random_force(args.id_path, 0, args.ntest)
    _, ood_test = load_fem_dataset_Q4_with_materials_and_random_force(args.ood_path, 0, args.ntest)
    print(f"In-distribution test set: {len(id_test)} samples ({args.id_path})")
    print(f"Out-of-distribution test set: {len(ood_test)} samples ({args.ood_path})")

    id_metrics = evaluate_dataset_hyperelastic_Q4(id_test, model, args, device, dtype)
    ood_metrics = evaluate_dataset_hyperelastic_Q4(ood_test, model, args, device, dtype)

    id_val_error = 0.5 * (id_metrics["mean_rel_L2_u"] + id_metrics["mean_rel_L2_v"])
    ood_val_error = 0.5 * (ood_metrics["mean_rel_L2_u"] + ood_metrics["mean_rel_L2_v"])
    degradation_factor = (ood_val_error / id_val_error) if id_val_error > 0 else None

    report = {
        "geometry": args.geometry,
        "material": args.material,
        "checkpoint": args.checkpoint,
        "id_path": args.id_path,
        "ood_path": args.ood_path,
        "ntest": args.ntest,
        "in_distribution": {**id_metrics, "val_error": id_val_error},
        "out_of_distribution": {**ood_metrics, "val_error": ood_val_error},
        "degradation_factor": degradation_factor,
    }

    print("\n" + "=" * 80)
    print("OOD EVALUATION SUMMARY")
    print("=" * 80)
    print(f"In-distribution val_error:     {id_val_error:.4e}")
    print(f"Out-of-distribution val_error: {ood_val_error:.4e}")
    if degradation_factor is not None:
        print(f"Degradation factor (OOD/ID):   {degradation_factor:.2f}x")
    print("=" * 80)

    if args.out_json:
        with open(args.out_json, "w") as f:
            json.dump(report, f, indent=2)
        print(f"Full report written to {args.out_json}")
    else:
        print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
