"""Wraps the two round-6 cells into real .ipynb notebooks.

The .py files are meant to be pasted into a Colab cell. Handing them to
Colab as files makes it try to parse them as notebook JSON, which fails with
`Unexpected token '#'`. These are actual notebooks, so a Colab link opens
them directly.

Every source line keeps its trailing newline -- nbformat stores a cell's
source as a list of lines and Jupyter concatenates it verbatim, so a missing
"\\n" glues lines together into a SyntaxError. That bug shipped once already;
check_notebooks.py exists to catch it and is run at the end of this script.
"""
import os
import json
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

NOTEBOOKS = {
    "Round6_B2_Retrain.ipynb": (
        "cell_b2_retrain_and_eval.py",
        ["# B2 zero-shot: retrain on the repaired data, then re-evaluate\n",
         "\n",
         "All three B2 cases produced relative errors of **8 to 14.5** — 800% to\n",
         "1450%, against 5.0-10.6% for the three B1 cases — and nearly flat in the\n",
         "mesh. Their cached load had been overstated by a factor that **depended\n",
         "on the mesh**, about 13x at N=21 against 21x at N=33, which for a study\n",
         "that measures transfer across meshes invalidates them outright.\n",
         "\n",
         "The caches are repaired and checked. The models fitted to the bad load\n",
         "are gone. This notebook does the half that was never done: **retrain,\n",
         "then re-evaluate**.\n",
         "\n",
         "* **NEEDS A GPU.** ~45 min per case to train on an A100.\n",
         "* **The eval is cheap** — the twenty N=101 references per case are\n",
         "  cached and were never touched by the load bug, so the eight hours the\n",
         "  B1 evals took do not recur. The cell prints the cached count per case\n",
         "  before starting, so the real cost is visible up front.\n",
         "* **Resumable** at every stage.\n",
         "\n",
         "**It carries one hard-won correction.** Report section 9.1 established\n",
         "that once B2's boundary force is FEM-consistent, correcting it *alone*\n",
         "makes accuracy **worse** — 32.46% to 94.08% — because the smaller,\n",
         "correct force weakens the only gradient pulling the network off the\n",
         "all-zero solution. `train_B2.py` fixes that with `--loss_force_norm`,\n",
         "on by default. The zero-shot trainer had no such option, and the first\n",
         "retrain attempt was reproducing that exact regression (combined val\n",
         "error 0.96 at epoch 25, 1.13 at epoch 50) before it was stopped. The\n",
         "option is now ported, its default resolved from the geometry, and\n",
         "printed at the top of every run.\n",
         "\n",
         "So the first thing to look for in the output is:\n",
         "\n",
         "```\n",
         "[loss_force_norm] not given; resolved to 1 from geometry B2.\n",
         "```\n",
         "\n",
         "If that line is missing, the code did not update — stop and say so.\n"]),
    "Round6_Check_B2_FixedSel_Status.ipynb": (
        "cell_check_b2_fixedsel_status.py",
        ["# How far did the B2 fixed-selection training actually get?\n",
         "\n",
         "**Read-only, changes nothing, no GPU needed.** Run this before\n",
         "(re)launching `Round6_B2_FixedSelection_All.ipynb` after any\n",
         "disconnect, to see whether Drive already holds usable progress for\n",
         "Mooney-Rivlin and/or Arruda-Boyce instead of guessing.\n",
         "\n",
         "For each material, reports the furthest stage reached:\n",
         "`zeroshot_eval.json` (fully done) > `EARLY_STOPPED` marker >\n",
         "`metrics_history.json` (last and best validation event) >\n",
         "`train_state_latest.pt` (the epoch a restart will resume from) >\n",
         "nothing (never started).\n",
         "\n",
         "Seconds to run — it only reads small JSON/checkpoint metadata files,\n",
         "no training and no model forward pass.\n"]),
    "Round6_MMS_Operator_PerMember.ipynb": (
        "cell_mms_operator_per_member.py",
        ["# MMS operator — consistency across its own family\n",
         "\n",
         "Answers the open question under point 9: is the operator consistent\n",
         "across the 16-member manufactured family, or only consistent on\n",
         "average? `mms_operator.py` only ever kept the family MEAN; this loads\n",
         "the three checkpoints its N=9/17/33 runs already wrote and re-scores\n",
         "each of the 16 test members individually, no retraining.\n",
         "\n",
         "* Needs no GPU strictly, but will use one if available.\n",
         "* **Minutes, not hours** — three forward-pass sweeps of 16 samples\n",
         "  each. Compare the printed std/mean against\n",
         "  `Q4_spread_stdev_over_mean` in\n",
         "  `point9_results/mms_family_fem_B1_neo_hookean.json` — same family,\n",
         "  same meshes, same quantity.\n",
         "* A missing checkpoint is reported and that mesh skipped, not fatal.\n"]),
    "Round6_Pareto_B2_ArrudaBoyce_Only.ipynb": (
        "cell_pareto_B2_arruda_boyce_only.py",
        ["# Accuracy/cost Pareto — B2 x Arruda-Boyce ONLY\n",
         "\n",
         "Use this instead of `Round6_Pareto_B2.ipynb` when Neo-Hookean is\n",
         "already done and Mooney-Rivlin is mid-sweep in another Colab\n",
         "session — that other notebook's PRE-FLIGHT ran before\n",
         "Arruda-Boyce's checkpoint existed and will never notice it now.\n",
         "This cell only ever touches Arruda-Boyce's own files, so it is\n",
         "**safe to run at the same time**, in its own runtime, with zero\n",
         "risk to the other two materials.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* **Cost is not measured for this material yet.** B2 x\n",
         "  Neo-Hookean's own Pareto took 7h11m end to end; Arruda-Boyce's\n",
         "  CPU assembly is 2.1-2.4x costlier per B1's numbers (Table 18b),\n",
         "  so budget more than that, not less.\n",
         "* **Resumable** at every resolution.\n"]),
    "Round6_Pareto_B2_MooneyRivlin_Only.ipynb": (
        "cell_pareto_B2_mooney_rivlin_only.py",
        ["# Accuracy/cost Pareto — B2 x Mooney-Rivlin ONLY\n",
         "\n",
         "Use this instead of `Round6_Pareto_B2.ipynb` when Arruda-Boyce is\n",
         "already mid-sweep in another Colab session\n",
         "(`Round6_Pareto_B2_ArrudaBoyce_Only.ipynb`). That other notebook's\n",
         "general-purpose sibling walks straight from Mooney-Rivlin into\n",
         "Arruda-Boyce the moment its own nine resolutions finish, with no\n",
         "pause — and both would then write the same\n",
         "`pareto_B2_arruda_boyce.json`, each holding its own in-memory copy\n",
         "read once at start. Whichever finishes and writes last can\n",
         "silently overwrite resolutions the other already saved. This cell\n",
         "only ever touches Mooney-Rivlin's own files, so it is **safe to run\n",
         "at the same time**, in its own runtime, with zero risk to\n",
         "Arruda-Boyce's file.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* **Resumable** at every resolution — a restart picks up exactly\n",
         "  where an interrupted run left off.\n"]),
    "Round6_Pareto_B2.ipynb": (
        "cell_pareto_B2.py",
        ["# Accuracy/cost Pareto — the three B2 cases\n",
         "\n",
         "The B2 side of round-5 point 2, on the same script and the same nine\n",
         "resolutions as the B1 Pareto. **Does not wait for all three B2\n",
         "checkpoints** — Neo-Hookean's is done (2026-09-01 fixed-selection\n",
         "rerun) and this runs for it now; Mooney-Rivlin and Arruda-Boyce are\n",
         "reported as \"no checkpoint yet\" and skipped until\n",
         "`cell_b2_fixed_selection_all.py` finishes them, at which point\n",
         "re-running this cell picks them up.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* **Cost is not measured for B2 yet.** B2's assembly cost is within 2%\n",
         "  of B1's for the same material (report section 4.2), so B1's numbers\n",
         "  are the closest guide, not a B2 measurement: Neo-Hookean took\n",
         "  1 h 54 m to 6 h 24 m, Mooney-Rivlin 14 h 31 m end to end — the\n",
         "  material, not the geometry, is what drives the difference (Table 4a).\n",
         "* **Resumable** at every resolution within a case, and a case whose\n",
         "  JSON already holds all nine resolutions is skipped entirely.\n",
         "\n",
         "Run this in its own Colab runtime, separate from whatever is running\n",
         "the B2 training or the B1 Pareto — three independent GPU jobs, so they\n",
         "do not share state and do not need to run in any particular order.\n"]),
    "Round6_Pareto_B1.ipynb": (
        "cell_pareto_remaining_B1.py",
        ["# Accuracy/cost Pareto — the two remaining B1 cases\n",
         "\n",
         "Round-5 point 2, already done for B1 x Neo-Hookean (report Table 18).\n",
         "This runs the same study for **Mooney-Rivlin** and **Arruda-Boyce**,\n",
         "whose zero-shot checkpoints are valid, so the Pareto can be stated on\n",
         "three materials instead of one.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* **Budget ~2 h per case, and do not be surprised by three times that.**\n",
         "  The two B1 x Neo-Hookean runs took 1 h 54 m and 6 h 24 m for the SAME\n",
         "  configuration on different Colab runtimes. An earlier note in\n",
         "  PROJECT_STATUS said \"minutes\"; that was wrong.\n",
         "* **Resumable**: a case whose JSON already exists is skipped.\n",
         "\n",
         "Why it costs that much: the Pareto draws its own problem instances\n",
         "(seeds 900_000 + i) and needs one fine FEM solve at N=101 per sample as\n",
         "the shared reference. Those are not the zero-shot study's references —\n",
         "different seeds, different problems — so they cannot be borrowed.\n",
         "\n",
         "Both checkpoints are checked before either case starts, so a missing\n",
         "one costs a second rather than two hours. Independent of the B2 retrain\n",
         "and the CG check; all three can run at the same time on separate\n",
         "runtimes.\n"]),
    "Round6_MMS_Operator_Rate.ipynb": (
        "cell_mms_operator_rate.py",
        ["# Does the MMS operator have a convergence rate of its own?\n",
         "\n",
         "**Optional, and cheap.** Section 8.11 names this as a limitation in\n",
         "its own words: *\"The operator was trained and scored at one mesh only,\n",
         "so it has no convergence rate of its own and cannot appear in Table 23;\n",
         "producing one means a training run per refinement, not a solve per\n",
         "refinement.\"*\n",
         "\n",
         "This does those training runs. N=17 is already measured; adding **N=9\n",
         "and N=33** gives three points, the same number Table 23 fits Q4 and Q9\n",
         "on.\n",
         "\n",
         "* **~1 hour**, and bounded — nothing here can run away.\n",
         "* GPU preferred; the FEM references are FP64 on CPU and at N=33 they\n",
         "  are the slower half.\n",
         "* **Resumable**: a resolution whose JSON exists is skipped.\n",
         "\n",
         "**A flat result is still a result.** Unlike Q4 and Q9, the operator has\n",
         "no theoretical rate to be checked against, so whatever comes out is a\n",
         "measurement rather than a verification. If its error does not improve\n",
         "with the mesh, that is worth reporting plainly: an operator whose error\n",
         "ignores refinement is a different object from a discretization whose\n",
         "error does not.\n",
         "\n",
         "The Q4 rates are computed alongside as a **control** — they should land\n",
         "near Table 23's 1.98 and 1.00. If they do not, this run is not\n",
         "comparable to that table and the operator rates should not be quoted.\n"]),
    "Round6_B2_BatchSize_Diagnostic.ipynb": (
        "cell_b2_batchsize_diagnostic.py",
        ["# Why will B2 zero-shot not train?\n",
         "\n",
         "`loss_force_norm` was necessary and **is not sufficient**. With it on,\n",
         "all three B2 cases still peaked at their FIRST validation and got worse\n",
         "from there — best combined val 0.9986, 0.9752, 1.0267 — and evaluated\n",
         "at 0.87-0.89, flat in the mesh to the fourth decimal. That is a model\n",
         "that never learned.\n",
         "\n",
         "**The candidate**: `b2_accuracy_search.py`'s `lossnorm` trial reached\n",
         "9.11% on this exact case, and it calls `train_B2.py` without\n",
         "`--batch_size`, i.e. at that script's default of **1**. The zero-shot\n",
         "trainer defaults to **8**. B1 is unaffected — it uses 8 on both sides\n",
         "and trains fine.\n",
         "\n",
         "**This is a candidate, not a diagnosis.** The last candidate did not\n",
         "hold, so this cell tests it: two arms on one case at **matched\n",
         "optimizer steps**, batch 8 against batch 1. Equal steps and not equal\n",
         "epochs, because at batch 1 an epoch is 800 steps rather than 100 and\n",
         "equal epochs would hand one arm eight times the training.\n",
         "\n",
         "* **~15-20 min** on an A100.\n",
         "* Early stopping is off in both arms, so each runs its full budget.\n",
         "* Neither arm writes to the real case directory.\n",
         "\n",
         "It prints one of three verdicts, including the one where batch size is\n",
         "**not** the cause — in which case it names the next candidates rather\n",
         "than leaving you to guess.\n"]),
    "Round6_B2_InputNorm.ipynb": (
        "cell_b2_input_norm.py",
        ["# Does standardising the input channels fix B2 zero-shot?\n",
         "\n",
         "The B1 control arm did its job. Same trainer, same protocol, B1\n",
         "reaches 0.066 and B2 sits at ~1.0, and the probe says how they differ:\n",
         "\n",
         "| | B1 | B2 |\n",
         "|---|---|---|\n",
         "| descent captured | **100%** | **47%** (37-60%) |\n",
         "| correlation | +0.997..+0.9996 | +0.87 down to **-0.11** |\n",
         "| amplitude ratio | 0.98-1.02 | **0.23-0.61** |\n",
         "| roughness | **1.01x** | **3.00x** |\n",
         "| rms(f)/rms(E) fed in | 6.1e-4 - 8.2e-4 | **2.3e-5 - 7.2e-5** |\n",
         "\n",
         "Roughness is `(U ratio)/(amplitude ratio)^2` -- 1.0 for a field as\n",
         "smooth as the truth. B2 carries **three times** the strain energy its\n",
         "size warrants: its field is **rough, not merely small**, so rescaling\n",
         "cannot fix it, and the `Pi(s*pred)` scan agrees (s = 1.0 on six of\n",
         "eight).\n",
         "\n",
         "**The one candidate the control singles out** is the input channels:\n",
         "the two carrying the load are **10-30x quieter** relative to stiffness\n",
         "on B2 than on B1, and nonzero on 3-5% of nodes. On top of that B2\'s\n",
         "per-node load scale changes **1.98x** between its two training meshes\n",
         "while the total is constant to 0.001% -- same physics, two numbers.\n",
         "\n",
         "**This is not the difference between the arms** -- neither run used any\n",
         "normalisation. It is a candidate *remedy* for a condition that is much\n",
         "worse on B2, and it may not work. **If the normalised run also lands\n",
         "near 1.0, the input scaling is not the obstacle** and the next place to\n",
         "look is the Dirichlet ramp or the parametric family.\n",
         "\n",
         "**Needs a GPU, ~15 min, one arm. Nothing touches the real run.**\n"]),
    "Round6_B2_SingleResolution.ipynb": (
        "cell_b2_single_resolution.py",
        ["# Does B2 train at ONE resolution? The test that splits what is left\n",
         "\n",
         "Six candidates are now closed: the load, `loss_force_norm`, batch\n",
         "size, the data-and-functional (Π\'s minimum **is** at `uv_exact`,\n",
         "W/U = 2.000), input normalisation, and — from the run just done — the\n",
         "**Dirichlet ramp**:\n",
         "\n",
         "| | B1 | B2 | ratio |\n",
         "|---|---|---|---|\n",
         "| rms(raw demanded)/rms(output) | 1.72x | 2.00x | **1.16x** |\n",
         "| peak/rms of the raw demanded | 2.44 | 2.46 | **1.01x** |\n",
         "\n",
         "Against a **15x** gap in final error, a 16% difference in what the\n",
         "mask asks for explains nothing. The ramp is dead.\n",
         "\n",
         "**Two differences remain** from the B2 model that *does* work (9.11%,\n",
         "`train_B2.py`, same geometry and energy): the **data family** (GRF in\n",
         "(θ,r) vs Fourier in θ alone) and **joint training** (one mesh vs two).\n",
         "\n",
         "Guessing between them is what the last five rounds did. This\n",
         "**separates** them: train B2 at N=21 alone and at N=33 alone.\n",
         "\n",
         "* **both reach ~0.07** → joint training is the fault, and that is a\n",
         "  reportable finding since resolution invariance is the claim.\n",
         "* **both stay ~1.0** → the parametric family is all that is left, and\n",
         "  testing it costs *hours* of FEM — decide before spending it.\n",
         "* **one of each** → a resolution-specific problem, much narrower.\n",
         "\n",
         "**Either way it ends a guess instead of starting one. GPU, under half\n",
         "an hour, nothing touches the real run.**\n"]),
    "Round6_B2_EnergyVsError.ipynb": (
        "cell_b2_energy_vs_error.py",
        ["# Does training lower Π while raising the error?\n",
         "\n",
         "The single-resolution run closed the seventh candidate — **joint\n",
         "training is not the fault**, both arms fail alone (0.9622 and 1.0372\n",
         "against the joint run's 0.9986, where B1 reaches 0.066–0.083).\n",
         "\n",
         "But it printed something sharper than its own verdict, and it is the\n",
         "same in **both** arms and in every other B2 run on record: **the best\n",
         "model is the first validation event, epoch 50, and all eight after it\n",
         "are worse.** Training does not stall on B2 — it walks the model away\n",
         "from the FEM solution. None of the closed candidates explains that;\n",
         "the load, the ramp and the family are properties of the problem, and\n",
         "none of them would make 20,000 further steps actively harmful.\n",
         "\n",
         "So: **is Π lower at epoch 450 than at epoch 50?**\n",
         "\n",
         "* **Π down, error up** → the optimizer is descending correctly toward\n",
         "  a field with *less energy than the FEM solution*. The discretised\n",
         "  functional does not have `uv_exact` as its minimiser over what this\n",
         "  network can reach. Structural and reportable — and it makes\n",
         "  regenerating the cache from the GRF the **wrong** next spend.\n",
         "* **Π up** → the optimizer is not minimising its own objective. An\n",
         "  optimisation failure; learning rate and the gradient through the\n",
         "  two-ramp mask, both cheap to test.\n",
         "\n",
         "The earlier functional check cannot answer this: it scanned\n",
         "Π(s·`uv_exact`) along **one ray** and found the minimum at s = 1.0.\n",
         "That proves `uv_exact` is stationary under rescaling, not that no\n",
         "other field has lower Π. This looks off the ray, at the two fields\n",
         "training actually produced.\n",
         "\n",
         "**CPU, a few minutes, trains nothing, writes nothing** — both saved\n",
         "endpoints already exist and the probe already prints Π(pred) beside\n",
         "Π(`uv_exact`).\n"]),
    "Round6_Val_Metric_Check.ipynb": (
        "cell_val_metric_check.py",
        ["# The two metrics disagree about which model is better\n",
         "\n",
         "The energy-vs-error run answered its question — **Π fell in both\n",
         "arms** (−2.48e−02 → −4.34e−02 and −3.26e−02 → −4.40e−02), descent\n",
         "captured rose 44%→76% and 59%→80%, and the field got *smoother*\n",
         "(2.32×→1.74×, 2.04×→1.73×). But its conclusion — that Π must prefer\n",
         "some field other than the FEM solution — **does not survive the\n",
         "per-sample numbers and is withdrawn.**\n",
         "\n",
         "**The probe's own error went DOWN on all eight samples it looked\n",
         "at**, one of them to 0.0930, which is B1 territory. And every\n",
         "negative correlation at epoch 50 is positive at epoch 450.\n",
         "\n",
         "Meanwhile the trainer says epoch 450 is **1.27× worse**. The two\n",
         "numbers are not the same metric:\n",
         "\n",
         "| | |\n",
         "|---|---|\n",
         "| the trainer | `0.5·( rms(e_u)/rms(u) + rms(e_v)/rms(v) )` |\n",
         "| the probe | `rms(e)/rms(uv_exact)`, both components at once |\n",
         "\n",
         "The trainer's divides each component by **its own** size, so a small\n",
         "component's ratio dominates the average however well the field as a\n",
         "whole is predicted.\n",
         "\n",
         "**And that metric is what early stopping used.** If it ranks these\n",
         "models backwards, every B2 run stopped at its *first* validation and\n",
         "kept the worse model — which is the pattern in every B2 run on\n",
         "record.\n",
         "\n",
         "Four samples are four samples, so this runs **both metrics on all\n",
         "100 val samples** of each resolution, for both checkpoints of both\n",
         "arms, with the per-component ratios and component sizes beside them.\n",
         "\n",
         "**CPU, a few minutes, trains nothing.**\n"]),
    "Round6_RUN_THIS.ipynb": (
        "bootstrap_cell.py",
        ["# Run any round-6 cell — always the current version\n",
         "\n",
         "**Use this notebook instead of the others.** Every other notebook\n",
         "here holds its own *copy* of the code, so once it is open in Colab\n",
         "it keeps running that copy no matter what is pushed. Its first\n",
         "lines `git reset --hard` the checkout at `/content/OMAR`, which\n",
         "updates the modules it calls but **not the cell itself** — so the\n",
         "new commit hash prints directly above the old output.\n",
         "\n",
         "That has now cost three runs:\n",
         "\n",
         "* the Pareto cell printed `ALREADY DONE, will skip` under a commit\n",
         "  whose code says `COMPLETE (9/9)`;\n",
         "* the single-resolution cell recommended hours of FEM that a later\n",
         "  commit had already ruled out;\n",
         "* the B1 metric cell printed a verdict the checked-out commit had\n",
         "  explicitly withdrawn.\n",
         "\n",
         "**This cell has no logic of its own to go stale.** It updates the\n",
         "repo, prints the commit it is on, and executes whichever\n",
         "`cell_*.py` you name — as that file exists on the branch right now.\n",
         "\n",
         "Set `CELL` to the file you want. A wrong name prints the full list.\n"]),
    "Round6_B2_FixedSelection_All.ipynb": (
        "cell_b2_fixed_selection_all.py",
        ["# The other two B2 cases, with the selection fixed\n",
         "\n",
         "All three B2 cases peaked at their **first or second validation\n",
         "event** out of a 2,000-epoch budget:\n",
         "\n",
         "| case | best epoch | optimiser steps | best val (old metric) |\n",
         "|---|---|---|---|\n",
         "| neo_hookean | 25 | 2,500 | 0.9986 |\n",
         "| mooney_rivlin | 25 | 2,500 | 0.9752 |\n",
         "| arruda_boyce | 225 | 22,500 | 1.0267 |\n",
         "\n",
         "That is not three materials failing — it is **one early-stopping\n",
         "criterion firing three times**. On B2 the per-component metric\n",
         "*rises* while the model improves.\n",
         "\n",
         "Neo-Hookean, rerun with `--selection_metric both_components`,\n",
         "needed **275,000 optimiser steps** (epoch 2,750 of 4,000, 3 h 18 m)\n",
         "to reach **0.0330** against its old 0.9986. Mooney-Rivlin was given\n",
         "**0.9%** of those steps and Arruda-Boyce **8%**. They were not\n",
         "measured; they were stopped. This cell measures them.\n",
         "\n",
         "**The cell types no numbers in.** It reads the Neo-Hookean record\n",
         "and the B1 span from the committed JSONs at run time and\n",
         "cross-checks the record against the live file on Drive, so a stale\n",
         "pasted copy cannot print a figure the repo has since corrected.\n",
         "\n",
         "**It cannot tell you in advance what these two will reach.** One\n",
         "corrected case is one case; the shared defect is a reason to expect\n",
         "improvement, not a measurement of it. A prediction made before the\n",
         "Neo-Hookean rerun was wrong by a factor of twenty, so no target is\n",
         "printed.\n",
         "\n",
         "**⚠️ The cell refuses to start until the Neo-Hookean zero-shot eval\n",
         "is complete on Drive.** These two cases are ~7.5 h of GPU spent on\n",
         "that premise; the gate checks it rather than trusting anyone to\n",
         "remember, and prints the Neo-Hookean numbers so you can judge them\n",
         "before committing the time.\n",
         "\n",
         "**~3 h 46 m per case** at the measured 3.387 s/epoch, less if it\n",
         "early-stops — Neo-Hookean stopped itself at 3,500 of 4,000. The\n",
         "eval that follows each is **seconds**: its twenty N=101 references\n",
         "are already cached per case, which is why both old evals produced\n",
         "all seven rows. Resumable at every validation event; a case whose\n",
         "eval is complete is skipped.\n",
         "Each case writes to a NEW directory and both caches are copied in —\n",
         "nothing regenerates the 7-hour sample caches, and no existing run is\n",
         "touched.\n"]),
    "Round6_Drive_Audit.ipynb": (
        "cell_drive_audit.py",
        ["# Full Drive audit — every file, opened and read\n",
         "\n",
         "`cell_check_results.py` looks for a fixed list of filenames. That\n",
         "answers *\"is the file I expected there?\"* and is blind to anything\n",
         "nobody thought to pattern-match — which is exactly what an audit is\n",
         "for.\n",
         "\n",
         "This walks the whole `pfem_run` tree:\n",
         "\n",
         "* every file listed with size and time;\n",
         "* every JSON opened and summarised **by what it contains**, not by\n",
         "  its name;\n",
         "* every checkpoint fingerprinted, and every result file tied back to\n",
         "  the checkpoint that produced it — an orphaned fingerprint is\n",
         "  flagged;\n",
         "* every study checked for **completeness** (Pareto 9 resolutions,\n",
         "  zero-shot eval 7, MMS family 3 meshes), so a half-finished file is\n",
         "  never read as finished;\n",
         "* leftover `.tmp` files, `EARLY_STOPPED` markers and unreadable JSON\n",
         "  all reported.\n",
         "\n",
         "Verified against all 26 result files in the repo before shipping: 0\n",
         "failures. **Read-only, a couple of minutes.**\n"]),
    "Round6_Print_All_Final_Results.ipynb": (
        "cell_print_all_final_results.py",
        ["# Print every final result, plainly — for reading, not for me\n",
         "\n",
         "For checking the report and summary by eye, not by trusting my own\n",
         "verification. Clones the repo and opens every committed result JSON\n",
         "that a report table is built from — the same files `report_builders/`\n",
         "reads — and prints each one, labeled with the Table number it belongs\n",
         "to, so this output can sit next to the `.docx` and be checked line by\n",
         "line.\n",
         "\n",
         "* **Read-only. No GPU. Seconds to run.** Nothing is recomputed and\n",
         "  nothing is written — it only opens files already on the repo.\n",
         "* Every section was tested locally against the real committed JSON\n",
         "  before this notebook was built, so the field names actually match\n",
         "  what is in the files (two files, B1 × Neo-Hookean's Pareto and the\n",
         "  progressive-OOD sweep, had different field names than the rest and\n",
         "  needed their own handling — caught by that test run, not left for\n",
         "  you to hit as a crash).\n",
         "* Where a clean table wasn't built for a section, the full JSON is\n",
         "  printed instead — un-truncated on purpose, so nothing is hidden\n",
         "  past an arbitrary character cutoff.\n"]),
    "Round6_B1_Metric_Recheck.ipynb": (
        "cell_b1_metric_recheck.py",
        ["# Are B1's reported numbers affected by the same metric?\n",
         "\n",
         "**Confirmed on all 100 val samples of each resolution, both arms:**\n",
         "\n",
         "| arm | checkpoint | per_component | both_components |\n",
         "|---|---|---|---|\n",
         "| N=21 | epoch 50 | 0.9622 | 0.7743 |\n",
         "| N=21 | epoch 450 | **1.2255** ↑ | **0.6858** ↓ |\n",
         "| N=33 | epoch 50 | 1.0372 | 0.7043 |\n",
         "| N=33 | epoch 450 | **1.1538** ↑ | **0.6822** ↓ |\n",
         "\n",
         "The metric early stopping used **ranks the two checkpoints\n",
         "backwards**, so every B2 run stopped at its *first* validation event\n",
         "and kept the worse model. Fixed in the trainer: `--selection_metric`\n",
         "now defaults to `both_components`, and both numbers are recorded.\n",
         "\n",
         "**What this does NOT mean.** B2 is still bad — best\n",
         "both-components error 0.68 against B1's 0.066. The metric cost B2\n",
         "0.77 → 0.69, an eighth of the gap, not the gap. **B2 zero-shot\n",
         "failing is not a metric artefact and the report's conclusion does\n",
         "not change.**\n",
         "\n",
         "**Why it inverts:** the per-sample `rms(v)/rms(u)` averages **1.90**\n",
         "while the ratio of the averaged components is **0.90** — a skewed\n",
         "distribution, so the average reports its tail.\n",
         "\n",
         "**And that is why B1 must be checked.** Every B1 number in the\n",
         "report — 5.0–10.6% zero-shot, 0.0658–0.0827 on the training meshes —\n",
         "is the same metric.\n",
         "\n",
         "* **B1's two metrics agree** → the reported numbers stand, and the\n",
         "  fact that the metric inverts on the annulus but not the block is\n",
         "  itself a finding about the geometry.\n",
         "* **B1's disagree too** → every zero-shot number is in a metric that\n",
         "  does not order models correctly, and the tables must be restated\n",
         "  before v38.\n",
         "\n",
         "**CPU, minutes, trains nothing. Run this before the report is\n",
         "touched.**\n"]),
    "Round6_MMS_Family.ipynb": (
        "cell_mms_family.py",
        ["# Q4 and Q9 over the manufactured family — closing point 9\n",
         "\n",
         "Timon\'s second email, on the MMS point: *\"Ideally, we do it for a\n",
         "parametrised family of solutions which will be a bit more time\n",
         "consuming.\"*\n",
         "\n",
         "Half of that is done and half has never been touched:\n",
         "\n",
         "* the **operator** is trained on a 64-member family and its mean over\n",
         "  the 16 held-out members is already recorded;\n",
         "* **Q4 and Q9 have never been scored on the family at all.** Tables\n",
         "  22, 23 and 24 are every one of them the single member\n",
         "  α = 0.05, β = 0.7.\n",
         "\n",
         "So the report\'s three-way comparison is a *single-member* comparison.\n",
         "This fills in the missing half. No new physics, no training —\n",
         "`mms_study.py` already takes `--alpha` and `--beta`, so this is that\n",
         "script in a loop, aggregated.\n",
         "\n",
         "**The members are the operator\'s own**, drawn with the identical\n",
         "`sample_family(ntest, seed + 1)` call, so both means are over the\n",
         "SAME 16 problems. **And (0.05, 0.7) is not among them** — checked — so\n",
         "this is a genuinely new measurement, not a re-dressing of Table 24.\n",
         "\n",
         "**CPU (FP64), about an hour and a half, bounded, resumable.**\n"]),
    "Round6_B2_Model_Probe.ipynb": (
        "cell_b2_model_probe.py",
        ["# What is the trained B2 model doing, and what is it fed?\n",
         "\n",
         "The functional check settled the previous question. Pi(s * uv_exact)\n",
         "was scanned over s on six samples at both training resolutions and the\n",
         "minimum landed at **s = 1.000 every time**, with |W|/U = 2.00 to three\n",
         "decimals. The cache is fine, the work term is fine, and the functional\n",
         "the trainer minimises really is minimised by the FEM solution.\n",
         "\n",
         "That rules out the data and leaves the training path. This looks at\n",
         "the path directly, with the checkpoint already on Drive.\n",
         "\n",
         "The first run returned real information **and** showed that two things\n",
         "in the probe itself were built wrong. Both are fixed here:\n",
         "\n",
         "* it printed `Pi(pred)` with no `Pi(uv_exact)` **for the same sample** --\n",
         "  the functional test reads `train_samples`, this reads `val_samples`,\n",
         "  and those are different problems, so the number could not be compared\n",
         "  with anything. Both are computed here now, per sample.\n",
         "* it put the channel scales at N=21 and N=33 side by side as if the\n",
         "  difference were a **mesh** effect. The cache seeds each resolution\n",
         "  differently, so those are different **draws** too. One fixed seed is\n",
         "  now rebuilt on both meshes, which is the controlled version.\n",
         "\n",
         "**And it adds the control that was missing.** B1 reaches 0.066 on the\n",
         "same trainer and protocol, so any account of B2\'s failure that applies\n",
         "equally to B1 explains nothing. Both arms run, printed for comparison.\n",
         "\n",
         "What the first run established: the model is **not** predicting zero,\n",
         "its amplitude is 2.5-4x too small, `W/U ~ 2` so **rescaling would not\n",
         "help**, `U(pred)` is nearly constant across every sample and both meshes\n",
         "while the targets span 3x, and it responds to its input about **five\n",
         "times too weakly**.\n",
         "\n",
         "**CPU, a couple of minutes, writes nothing, trains nothing.**\n"]),
    "Round6_B2_Functional_Check.ipynb": (
        "cell_b2_functional_check.py",
        ["# Is the cached FEM solution a minimum of the trainer's Pi?\n",
         "\n",
         "Two candidates tested, neither explains the B2 failure:\n",
         "`loss_force_norm` (necessary, not sufficient) and batch size\n",
         "(0.9888 against 0.9444 at matched steps — noise on curves swinging\n",
         "0.94 to 1.45).\n",
         "\n",
         "**The clue nobody used**: a relative error of 1.0 is not an arbitrary\n",
         "bad number. The metric is `0.5*(rms(e_u)/rms(u) + rms(e_v)/rms(v))`,\n",
         "and substituting `uv_pred = 0` gives exactly 1. All three B2 runs sat\n",
         "at 0.94–1.23. So the network is probably predicting nothing — and it\n",
         "may be doing so **correctly**, because a network that minimizes Pi\n",
         "goes wherever Pi's minimum is.\n",
         "\n",
         "That turns the question away from the optimizer entirely: is Pi's\n",
         "minimum, built from this cache's `node_forces`, anywhere near this\n",
         "cache's `uv_exact`? **No training needed to answer it.**\n",
         "\n",
         "It scans `Pi(s * uv_exact)` for s from 0 to 1.5. The true solution\n",
         "should win at s=1. If the minimum sits near s=0 the work term is too\n",
         "weak, the trainer is correctly finding zero, and **no optimizer\n",
         "setting will help** — the fault is in the data.\n",
         "\n",
         "* **Seconds. No GPU. Reads the cache, writes nothing.**\n",
         "* It asserts its stand-in field really does reproduce `uv_exact`\n",
         "  through the soft-Dirichlet ramp *before* reporting anything, so a\n",
         "  wrong assumption about the mask cannot pass itself off as physics.\n",
         "  If it stops on that assertion, that is the finding.\n"]),
    "Round6_Check_Results.ipynb": (
        "cell_check_results.py",
        ["# What is actually on Drive?\n",
         "\n",
         "Read-only. Shows which results exist and how far each got, so a run\n",
         "that printed nothing can be told apart from one that did nothing.\n",
         "Safe to run at any time, including while other notebooks are working.\n"]),
    "Round6_OOD_Progressive.ipynb": (
        "cell_ood_progressive.py",
        ["# Progressive OOD shift — Timon round 6, point 1\n",
         "\n",
         "Separates **material stiffness** from **loading** and sweeps the shift\n",
         "from 0 to 3σ, instead of the single 2–2.5σ pair Table 11 measured.\n",
         "\n",
         "* **CPU is fine** — no GPU needed.\n",
         "* **~1.5–4 h** for the full 19-cell grid at 10 samples each.\n",
         "* **Resumable**: every cell is written to Drive as it finishes and\n",
         "  skipped on a re-run. After a disconnect, just run the cell again.\n",
         "\n",
         "Edit `GEOMETRY`, `MATERIAL` and `CKPT` in the cell to pick the case.\n"]),
    "Round6_OOD_Progressive_Remaining.ipynb": (
        "cell_ood_progressive_remaining.py",
        ["# Progressive OOD shift — the other five cases (Timon round 8, point 2)\n",
         "\n",
         "B1 × Neo-Hookean is already done (Tables 19, 19a). Timon: \"OOD is\n",
         "well addressed and for the paper we should do that for the other\n",
         "cases.\" Runs the same protocol for B1×Mooney-Rivlin, B1×Arruda-Boyce,\n",
         "B2×Neo-Hookean, B2×Mooney-Rivlin, B2×Arruda-Boyce, in that order, each\n",
         "against its own Table 5/7/11 checkpoint (not the zero-shot\n",
         "fixed-selection checkpoints Tables 12/18 use).\n",
         "\n",
         "* **CPU is fine** — no GPU needed.\n",
         "* **~7.5–20 h total** across all five cases (each is the same 19-cell\n",
         "  grid the first case needed).\n",
         "* **Resumable at two levels**: this cell skips a whole case if its\n",
         "  output JSON already exists on Drive; within a case, every cell is\n",
         "  written as it finishes and skipped on a re-run. Just run the cell\n",
         "  again after any disconnect — expect to need several sessions.\n"]),
    "Round6_HighDOF_PeakStress.ipynb": (
        "cell_high_dof_stress_qoi.py",
        ["# High-DOF study + peak-stress QoI — Timon round 8, point 1\n",
         "\n",
         "Re-runs Table 6a's exact B1 × Neo-Hookean sweep (same resolutions,\n",
         "same ~10M-DOF reference) through `high_dof_convergence_study.py`,\n",
         "which now also reports a peak PK1 stress QoI alongside its existing\n",
         "L2/H1/energy-norm columns — the literal example (\"maximum stresses\n",
         "or similar\") Timon's email named for the point-1 tolerance-vs-cost\n",
         "check, which the field norms alone don't directly answer.\n",
         "\n",
         "* **Already points at the original Table 6a checkpoints**, found on\n",
         "  Drive 2026-09-06: `pfem_ckpt` has the ~10M-DOF fine reference\n",
         "  itself plus N=1001 and N=1401 already solved — those return\n",
         "  instantly, no re-solve. N=51/101/201/401/701 were NOT found\n",
         "  there and must be solved fresh: ~2.6 h total from Table 6a's own\n",
         "  recorded timings, not the 8–15+ h a fully-fresh run would need.\n",
         "  If that path has since moved, edit `CHECKPOINT_DIR` in the cell —\n",
         "  it just falls back to solving everything fresh.\n",
         "  GPU strongly required either way.\n",
         "* **Resumable at two levels**: `--checkpoint_dir` resumes a whole\n",
         "  solve, and `--cg_checkpoint_every` checkpoints CG's own internal\n",
         "  state — a disconnect anywhere loses at most a few thousand CG\n",
         "  iterations, never a whole solve. Just run the cell again.\n"]),
    "Round6_Precond_Recheck_Stage1.ipynb": (
        "cell_precond_recheck_stage1.py",
        ["# Preconditioner + peak-stress bug-fix re-check — Stage 1 (cheap)\n",
         "\n",
         "**Run this BEFORE Stage 2.** Two fixes landed since the first\n",
         "high-DOF/peak-stress run: (1) `compute_peak_stress_error` had a real\n",
         "bug — the \"reference\" peak stress was `max(|P|)` over the COARSE\n",
         "mesh's own Gauss points, a point set that gets denser (and so bigger)\n",
         "as N grows, so it silently drifted from 13.9 at N=51 to 39.3 at\n",
         "N=1401 instead of being one fixed target — fixed by comparing every\n",
         "resolution against the fine reference's own true peak-stress point,\n",
         "found once. (2) a new opt-in 2x2 block-Jacobi preconditioner\n",
         "(`--precond_kind block2x2`) exists to fix the CG failures the\n",
         "original run had at N=401 (20), 701 (30), 1001 (40), 1401 (80).\n",
         "\n",
         "A checkpoint marked \"done\" returns its OLD answer regardless of\n",
         "`--precond_kind`, so this cell deletes ONLY the N=401/701 checkpoints\n",
         "to force genuine fresh block2x2 solves there — N=51/101/201 and the\n",
         "fine reference keep resuming instantly, nothing about them needs\n",
         "re-testing.\n",
         "\n",
         "**Why not all four failing resolutions at once**: N=1001 and N=1401\n",
         "have never been solved fresh in this project — every past run\n",
         "free-rode on a pre-session checkpoint — so their real from-scratch\n",
         "cost with either preconditioner is unknown and could be large at\n",
         "2-4M DOF each. This stage answers \"does block2x2 even help\" on the\n",
         "two CHEAPER failing resolutions first (~27 + ~75 min with the OLD\n",
         "preconditioner is the known baseline) before committing to the\n",
         "expensive, unknown-cost Stage 2.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* Check the printed end-of-run checklist before running Stage 2:\n",
         "  did cg_failures at 401/701 improve, and is peak_stress_ref now\n",
         "  IDENTICAL across every row?\n"]),
    "Round6_Precond_Recheck_Stage2.ipynb": (
        "cell_precond_recheck_stage2.py",
        ["# Preconditioner + peak-stress bug-fix re-check — Stage 2 (expensive)\n",
         "\n",
         "**Only run this after Stage 1 finished and its checklist looked\n",
         "right** (CG failures reduced at N=401/701, peak_stress_ref identical\n",
         "across rows). If Stage 1 didn't help, re-think the preconditioner\n",
         "before spending the time this stage needs.\n",
         "\n",
         "Forces fresh block2x2 solves at N=1001 (~2,004,002 DOF) and N=1401\n",
         "(~3,925,602 DOF) — deletes their existing checkpoints, which predate\n",
         "this whole session and were solved with the old scalar Jacobi\n",
         "preconditioner (already hitting the CG cap 40 and 80 times). These\n",
         "two resolutions have NEVER been solved from scratch before in this\n",
         "project, so there is no reliable time estimate — expect this to be\n",
         "the single most expensive part of the whole re-check.\n",
         "\n",
         "Runs all 7 resolutions again (not just the 2 new ones) so the output\n",
         "is one final, directly comparable table rather than needing a manual\n",
         "merge — N=51/101/201/fine and (if Stage 1 ran) 401/701 all resume\n",
         "instantly, only 1001/1401 do new work.\n",
         "\n",
         "* **NEEDS A GPU. Potentially the longest single run in this project\n",
         "  — do not start this without having reviewed Stage 1's output.**\n"]),
    "Round6_MGV_Recheck_N401.ipynb": (
        "cell_mgv_recheck.py",
        ["# Geometric multigrid preconditioner — real-GPU test at N=401\n",
         "\n",
         "**block2x2 (the previous attempt) was measured to NOT help**: a real\n",
         "GPU re-run showed cg_failures at N=401/701 IDENTICAL to plain scalar\n",
         "Jacobi (20/30, unchanged), with essentially the same wall-clock. So\n",
         "a genuine geometric multigrid V-cycle was built instead\n",
         "(`multigrid_precond.py`) — the textbook-correct fix for CG stagnation\n",
         "on a structured elasticity grid, and one that stays fully\n",
         "matrix-free (never forms K), unlike the other option considered\n",
         "(incomplete Cholesky, which needs the actual sparse matrix and would\n",
         "undercut this whole solver's reason for existing).\n",
         "\n",
         "**Validated on CPU before this cell ever runs**\n",
         "(`validate_multigrid_precond.py`): the V-cycle solve reproduces the\n",
         "SAME converged displacement as the existing plain-Jacobi solve on\n",
         "both B1 and B2 (including B2's own partially-fixed-DOF nodes) to\n",
         "1e-12 relative difference, and its advantage over plain Jacobi GREW\n",
         "with problem size instead of staying flat — 3.0x fewer iterations at\n",
         "N=9, 5.2x at N=33, 9.7x at N=65. A growing advantage with N is the\n",
         "actual signature of correctly-functioning multigrid, which is why\n",
         "this is worth real GPU time where block2x2 was not.\n",
         "\n",
         "This cell forces a genuine fresh `--precond_kind mgv` solve at ONLY\n",
         "N=401 — the cheapest of the four resolutions that hit the CG\n",
         "iteration cap originally — by deleting its checkpoint first.\n",
         "N=51/101/201 and the fine reference resume instantly from their\n",
         "existing good checkpoints.\n",
         "\n",
         "**What to check**: did `cg_failures` at N=401 actually drop from 20\n",
         "(ideally to 0)? mgv costs more per CG iteration than Jacobi (each\n",
         "V-cycle does several matvecs across multiple mesh levels plus a\n",
         "coarse-level factorization), so judge the trade-off using BOTH\n",
         "cg_failures and wall_clock_s together — fewer failures at a similar\n",
         "or better wall-clock is a clean win; fewer failures but much slower\n",
         "is a real trade-off worth reporting honestly, not smoothing over.\n",
         "\n",
         "* **NEEDS A GPU.** Known baseline for N=401 with the OLD preconditioner:\n",
         "  ~27 min, 20 CG failures.\n",
         "* Only proceed to N=701/1001/1401 if this shows a genuine reduction\n",
         "  in cg_failures.\n"]),
    "Round6_MGV_Recheck_N701_1001_1401.ipynb": (
        "cell_mgv_recheck_n701_1001_1401.py",
        ["# Geometric multigrid preconditioner — real-GPU test at N=701, 1001, 1401\n",
         "\n",
         "**N=401 (previous notebook) converged cleanly** after fixing a real\n",
         "performance bug: cg_failures 20 → 0, wall-clock ~43.6 min (was ~87 min\n",
         "before that fix, ~27 min for the old, non-converging plain-Jacobi\n",
         "run). That cleared this item's own bar for proceeding to the\n",
         "remaining three target resolutions.\n",
         "\n",
         "**A second, more serious issue was found and fixed before this cell\n",
         "was written** — checked, not assumed: `coarsen_N` requires `(N-1)`\n",
         "even at every halving, so how deep a given N can coarsen depends on\n",
         "how many factors of 2 divide `(N-1)`, not on N's own size. N=401\n",
         "happened to coarsen 4 times down to ~1,300 free DOF (cheap to solve\n",
         "exactly). **N=701 and N=1401 only coarsen down to N=176 (~62,000 free\n",
         "DOF); N=1001 to N=126 (~32,000)** — an exact dense solve there would\n",
         "be computationally infeasible (tens of hours per factorization, ~20\n",
         "needed per solve). Fixed with a size-based fallback: below a\n",
         "threshold, the same exact dense solve N=401 used; above it (all three\n",
         "of these), an approximate matrix-free CG coarse solve instead — a\n",
         "standard, textbook multigrid variant. Validated on CPU that this\n",
         "fallback logic reproduces the same solution as the exact path on\n",
         "small test cases, before ever pointing it at these three real, much\n",
         "larger coarsest levels.\n",
         "\n",
         "**What is genuinely unknown**: none of N=701/1001/1401 has ever run\n",
         "this approximate coarse-solve path on real hardware. Rough\n",
         "linear-in-DOF extrapolations from N=401 give ~2.2h / ~4.5h / ~8.9h\n",
         "respectively — but that assumes multigrid's own iteration count\n",
         "stays flat with N, unproven at this scale. This cell exists to get\n",
         "real data points, not confirm a guess — read each resolution's\n",
         "printed numbers as they finish rather than assuming the estimates\n",
         "held.\n",
         "\n",
         "**All three run in ONE process, in order (701 → 1001 → 1401), so this\n",
         "is a single long Colab session (~15h combined, rough estimate) rather\n",
         "than three separate notebooks to babysit.** N=51/101/201/401 and the\n",
         "fine reference reuse their existing good checkpoints instantly.\n",
         "\n",
         "**Safely resumable if Colab disconnects mid-run**: each target N's\n",
         "checkpoint is force-reset to a fresh mgv solve only ONCE EVER, guarded\n",
         "by a marker file on Drive — re-running this exact cell after a\n",
         "disconnect does NOT re-delete an in-progress resolution's checkpoint\n",
         "(unlike naively re-running a plain reset-then-solve script would), it\n",
         "resumes from solve_matrix_free's own per-Newton-iteration checkpoint\n",
         "exactly where it left off, and any already-fully-finished resolution\n",
         "in this list resumes in seconds.\n",
         "\n",
         "* **NEEDS A GPU.** Known baselines with the OLD preconditioner: N=701\n",
         "  ~75 min/30 failures, N=1001 40 failures, N=1401 80 failures (all\n",
         "  unchanged by block2x2).\n",
         "* Rough combined time estimate: ~15h, explicitly uncertain — if\n",
         "  N=701 alone overshoots its own ~2.2h estimate, expect N=1001/N=1401\n",
         "  to overshoot by a similar factor too.\n",
         "* If Colab disconnects, just re-run this same cell — see the\n",
         "  resumability note above.\n"]),
    "Round6_MMS_Richer_ArrudaBoyce.ipynb": (
        "cell_mms_richer_remaining.py",
        ["# Richer-family MMS, Arruda-Boyce (round-8, point 6 follow-up)\n",
         "\n",
         "Closes a real gap Omar caught: the richer sine/cosine "
         "manufactured-solution family (built and verified for\n",
         "Neo-Hookean only) and the three-material MMS extension "
         "(Mooney-Rivlin/Arruda-Boyce, using the ORIGINAL single-mode\n",
         "field) had never been run together. This notebook runs the "
         "richer family for Arruda-Boyce specifically. Mooney-Rivlin is\n",
         "running the same study on CPU at the same time — not "
         "duplicated here.\n",
         "\n",
         "**Pure numerics, no neural network**: this verifies the FEM "
         "solver itself against a closed-form manufactured solution, not\n",
         "the trained operator. GPU is used when available since it "
         "speeds up the larger meshes (N=33) but isn't required for\n",
         "correctness.\n",
         "\n",
         "* Resumable — safe to re-run if interrupted.\n"]),
    "Round6_Measure_DD_NO_Latency.ipynb": (
        "cell_measure_dd_no_latency.py",
        ["# DD-NO inference latency (round-8, point 7 follow-up)\n",
         "\n",
         "Table 21a's break-even Comparison B (physics-informed vs. "
         "data-driven total cost of ownership) currently ASSUMES the\n",
         "data-driven operator's per-sample inference cost equals the "
         "physics-informed operator's own measured number (4.586 ms/sample,\n",
         "B1 x Neo-Hookean) — true by construction, since both use the "
         "identical `Transolver_Irregular_Mesh` architecture and inference\n",
         "time depends only on the forward-pass computational graph, not "
         "which loss trained the weights — but never actually measured for\n",
         "the DD-NO checkpoint specifically until now.\n",
         "\n",
         "**Standalone, no retraining, no risk**: `measure_inference_"
         "latency.py` only loads the already-trained DD-NO checkpoint and\n",
         "times its forward pass, the exact same script/protocol that "
         "produced the physics-informed operator's own Table 7 number.\n",
         "\n",
         "* No GPU-hours risk beyond a few minutes of timing runs. Requires "
         "a GPU runtime for the number to be comparable to Table 7's own\n",
         "  GPU-measured figure.\n"]),
    "Round6_TorchFEM_Comparison.ipynb": (
        "cell_torchfem_comparison.py",
        ["# GPU-FEM vs. torch-fem — efficiency comparison (item #13)\n",
         "\n",
         "Timon's round-7 email named this comparison directly, with no "
         "preference between torch-fem and TensorMesh (the library he\n",
         "mentioned first) — the only requirement is \"an efficient GPU "
         "implementation ... necessary for a fair comparison to a NO,\"\n",
         "which torch-fem satisfies. Done AFTER item #4 (the multigrid "
         "preconditioner fix) deliberately: comparing before fixing our\n",
         "own solver's preconditioner would have measured a configuration "
         "Timon had already flagged as suboptimal.\n",
         "\n",
         "**Scope**: the large-scale matrix-free solver (Table 20/20a/20b/"
         "20c in the report) at the same resolutions those tables use —\n",
         "N=401/701/1001/1401 — not the small-scale batched solver "
         "compared against the neural operator elsewhere.\n",
         "\n",
         "**Why this isn't just \"whose CG is faster\"**: torch-fem always "
         "explicitly assembles a sparse tangent stiffness matrix, even in\n",
         "its \"cg\" iterative mode (confirmed by reading its source) — the "
         "opposite of our own solver, which never forms K at all. This\n",
         "cell measures peak GPU memory for both solvers (not just "
         "wall-clock), since that is where the architectural difference\n",
         "should show up most clearly at the largest resolutions.\n",
         "\n",
         "**A real bug found in torch-fem along the way**: writing our "
         "Neo-Hookean energy with `torch.log(torch.linalg.det(F))` for\n",
         "ln(J) — a completely standard way to write it — makes torch-fem's "
         "own double-backprop tangent stiffness come out all-NaN at\n",
         "F=Identity (exactly where every solve starts), a known sharp "
         "edge in `det`'s double-backward. Fixed by using\n",
         "`torch.linalg.slogdet` instead (same value, stable gradient) — "
         "confirmed directly by computing the Hessian both ways.\n",
         "\n",
         "**Validated on CPU before this cell was written** (`python -m "
         "omar_pfem.torchfem_comparison <N>`): both solvers, given the\n",
         "identical mesh/material/BCs/load, converge to the same "
         "displacement field (relative difference ~2-5e-6 at N=11/21,\n",
         "well inside torch-fem's own float32 precision). This cell "
         "re-runs that same check once more before the real sweep.\n",
         "\n",
         "**RESULT (2026-09-08, real A100 run, N=401/701/1001)**: "
         "torch-fem is dramatically faster in wall-clock than our own\n",
         "matrix-free mgv solver — 6.26s/11.00s/14.46s vs. "
         "2615.8s/7205.4s/17314.8s, i.e. ~418x/655x/1197x, growing with N.\n",
         "Reported honestly with two caveats: the two solvers are not run "
         "at matched precision/tolerance (torch-fem forced to float32\n",
         "with loose tolerances vs. our float64/tight, which plausibly "
         "explains a large share of the gap), and \"ours\" own peak GPU\n",
         "memory was never captured this run (it resumed from a "
         "checkpoint rather than solving fresh) — Omar's own call once\n",
         "this was confirmed: accept the wall-clock-only comparison as "
         "sufficient, note the memory gap as a deliberately open item\n",
         "rather than spend the several more GPU-hours a real \"ours\" "
         "solve at these sizes would cost. N=1401 is now included too,\n",
         "added once the first three showed how cheap this sweep really "
         "is (torch-fem's own solve time stayed under 15s even at 2M\n",
         "DOF; \"ours\" resumes for free) — skips whatever is already in "
         "the output JSON.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* Resumable: skips any N already in the output JSON.\n",
         "* Report every number honestly, including any resolution where "
         "torch-fem wins — that is a legitimate answer to Timon's\n",
         "  question, not a failure to fix.\n"]),
    "Round6_Field_Snapshot_Grid.ipynb": (
        "cell_field_snapshot_grid.py",
        ["# Item #12: displacement-field snapshot grid across resolutions\n",
         "\n",
         "Omar's own direction for item #12 (converting tables into "
         "figures, per Timon's round-8 request): rather than a plain\n",
         "log-log line plot of the numbers already in Table 6a, build the "
         "same kind of side-by-side field-panel figure Timon's own group\n",
         "uses (VINO Figs. 7a/8d/9d; the PFEM/NOWS screenshots Omar "
         "shared) — one panel per mesh resolution, arranged in a row,\n",
         "each showing the actual displacement FIELD, not just a summary "
         "number.\n",
         "\n",
         "**No new solving happens here.** This reuses item #4's own "
         "already-converged checkpoints on Drive (the same ~14.86h of\n",
         "real GPU work already committed and written into the report) — "
         "each one already holds the converged free-DOF displacement.\n",
         "Loading and reshaping that into an image costs no new GPU time; "
         "the cell needs no GPU and finishes in seconds.\n",
         "\n",
         "**Output**: one PNG, 7 panels (N=51/101/201/401/701/1001/1401), "
         "each the |u| (displacement magnitude) field over B1's domain —\n",
         "the same convergence story Table 6a's numbers already tell "
         "(the field barely changes past N=201, where L2 error gets\n",
         "small), but as a picture instead of a table.\n",
         "\n",
         "* No GPU needed — pure CPU mesh regeneration + checkpoint load "
         "+ plotting.\n",
         "* Saves to `/content/drive/MyDrive/pfem_run/figures/"
         "fig_B1_resolution_grid.png` — fetch it from Drive afterward.\n"]),
    "Round6_Inventory_Drive_Images.ipynb": (
        "cell_inventory_drive_images.py",
        ["# Inventory every image already on Drive (read-only)\n",
         "\n",
         "Omar's own request: rather than a slow, one-page-at-a-time Drive-"
         "search-API inventory (a single subfolder,\n",
         "`B1_neo_hookean_inputnorm`, already turned out to hold 75+ "
         "candidate images on its own), walk the mounted Drive directly\n",
         "with plain Python filesystem calls — orders of magnitude faster, "
         "and covers everything in one pass.\n",
         "\n",
         "**Read-only**: lists and counts, changes nothing. Prints one row "
         "per folder that holds at least one image (count, total size,\n",
         "earliest/latest modification time, and a rough guess at whether "
         "it looks like a final figure or a candidate-selection sweep —\n",
         "many images clustered within a few hours strongly suggests the "
         "latter), plus a grand total. Also writes the full listing to\n",
         "`pfem_run/image_inventory.json` for offline review.\n",
         "\n",
         "* No GPU needed. Should finish in well under a minute.\n"]),
    "Round6_Project_Figures.ipynb": (
        "cell_project_figures.py",
        ["# Item #12: field-panel-grid figures, generated by the ORIGINAL "
         "study scripts themselves\n",
         "\n",
         "**Omar's own explicit direction**, after flagging a real risk in "
         "an earlier version of this item: a separate script that\n",
         "reconstructs a trained model's own hyperparameters independently "
         "could load the wrong ones for some checkpoint. Fixed not by\n",
         "double-checking that reconstruction, but by removing the "
         "reconstruction entirely — a new `--save_sample_plot` flag was\n",
         "added DIRECTLY to `resolution_invariance_zeroshot.py`'s `cmd_eval` "
         "and `ood_progressive.py`'s `main`, at the exact point each\n",
         "already computes a prediction. This cell re-invokes each study's "
         "OWN real original command (the same one that already produced\n",
         "Tables 12/19/25/26's own published numbers) with that one flag "
         "added — nothing about the model-loading or prediction code is\n",
         "re-derived, so there is nothing new to get wrong.\n",
         "\n",
         "**Verified additive and non-destructive** before trusting it: "
         "run twice locally against a small test checkpoint, once fresh\n",
         "and once resumed from a cached `out_json` — both produced the "
         "image, and the numeric output was byte-identical to the same\n",
         "command without the flag (see PROJECT_STATUS.md item #12).\n",
         "\n",
         "**Why re-running the whole project is fast**: every command "
         "below already ran to completion before this session — each\n",
         "script's own resumability logic detects that and skips "
         "recomputing it. The only new work is one extra sample per\n",
         "resolution/shift level, purely for the plot.\n",
         "\n",
         "* **A — FEM convergence (Table 6a/20), B1 Neo-Hookean.** No "
         "model here at all (the checkpoint is a raw converged solution\n",
         "  vector) — this section never had the risk described above.\n",
         "* **B — Zero-shot resolution (Table 12), B1 Neo-Hookean.** Real "
         "eval command from this checkpoint's own `run_manifest.json`.\n",
         "* **C — OOD shift (Tables 19/25), all 6 geometry x material "
         "cases.** Real checkpoints/commands from `cell_ood_progressive.py`\n",
         "  and `cell_ood_progressive_remaining.py` (already committed).\n",
         "* **D — DD-NO coarse-vs-fine (Table 26), B1 Neo-Hookean.** Same "
         "eval script as B, pointed at Table 26's own two checkpoints.\n",
         "\n",
         "**Each section is independent and wrapped in its own "
         "try/except** — if one checkpoint path does not match your "
         "actual\n",
         "Drive layout, that section prints its real error and the "
         "others still run. Fix the path constant named in that section\n",
         "and re-run just this cell.\n",
         "\n",
         "* No GPU strictly required for A; a GPU speeds up B/C/D's "
         "forward passes and C's small (N=21) FEM solves, but nothing\n",
         "  here is large-scale.\n",
         "* Saves every figure to "
         "`/content/drive/MyDrive/pfem_run/figures/` — fetch them from "
         "Drive afterward.\n"]),
    "Round6_DD_NO_Coarse_vs_Fine.ipynb": (
        "cell_dd_no_coarse_vs_fine.py",
        ["# DD-NO on coarse vs. fine FEM labels — Timon round 8, point 3\n",
         "\n",
         "Sharpened version of \"add a DD-NO comparison\": trains two\n",
         "data-driven operators on B1 × Neo-Hookean, one from FEM labels\n",
         "generated at N=13 (coarse) and one at N=33 (fine, one of the\n",
         "physics-informed model's own two joint-training resolutions), then\n",
         "zero-shot evaluates both at Table 12's same seven test resolutions\n",
         "against the same N=101 reference. Tests an asymmetry the\n",
         "physics-informed operator cannot have — its accuracy ceiling does\n",
         "not depend on any FEM label mesh, because it never trains on FEM\n",
         "labels at all.\n",
         "\n",
         "* **GPU strongly preferred** for the training stage.\n",
         "* **Cost is genuinely unmeasured** at N=13/N=33 — the cell\n",
         "  calibrates on 20 samples per resolution FIRST and prints the real\n",
         "  measured per-sample time before committing to the full run. Read\n",
         "  that output before leaving it unattended.\n",
         "* **Matches Table 21's budget exactly**: 800 train / 200 test\n",
         "  samples, 75,000 optimizer steps — for BOTH coarse and fine, so\n",
         "  the two runs differ only in label-generation resolution, not in\n",
         "  training budget (a mismatched budget would confound the two).\n",
         "* **Resumable** at every stage (generate/convert/train/eval, per\n",
         "  resolution) — each is skipped if its output already exists.\n"]),
    "Round6_Data_Driven.ipynb": (
        "cell_data_driven.py",
        ["# Data-driven operator — Timon round 5, point 7b\n",
         "\n",
         "The same Transolver, same mesh, same 800/200 split, same optimizer and\n",
         "the **same optimizer-step budget** — trained on FEM solutions instead of\n",
         "the energy functional. Only the loss differs, so the comparison isolates\n",
         "the training principle rather than the architecture.\n",
         "\n",
         "* **No new FEM solves** — the labels are already in the dataset.\n",
         "* **GPU strongly preferred**; CPU works but will be slow.\n",
         "* Expected to finish inside the physics-informed run's 48 minutes,\n",
         "  since a data loss skips the per-step energy assembly.\n",
         "\n",
         "The script also reports the **label-generation cost** the data-driven\n",
         "model implicitly requires and the physics-informed one does not — about\n",
         "5.7 h of CPU for 800 B1 × Neo-Hookean solves at Table 4a's measured rate.\n"]),
    "Round6_MMS.ipynb": (
        "cell_mms.py",
        ["# Method of manufactured solutions — round 5, point 9 (FEM half)\n",
         "\n",
         "Timon: *\"compare Q4, Q9 and the physics-informed Transolver against\n",
         "exactly the same analytical solution in L2, H1 and energy norms and\n",
         "also examine stress errors\"*, and *\"this is the last thing to do\"*.\n",
         "\n",
         "**This notebook is the FEM half: Q4 and Q9.** The operator half needs\n",
         "a body-force term in the energy functional and a body-force input\n",
         "channel — a separate piece of work, described in `mms_study.py`.\n",
         "\n",
         "**The fork Timon left open is resolved here as body force**, because a\n",
         "body-force-free exact solution on this geometry is a homogeneous\n",
         "deformation, which Q4 reproduces to machine precision — the study\n",
         "would measure round-off and distinguish nothing.\n",
         "\n",
         "* **GPU optional.** FP64, so a T4/L4 buys little; `--cpu` is fine.\n",
         "* **Minutes** for N up to 33.\n",
         "* **Resumable**: each (order, N) row is appended as it finishes.\n",
         "\n",
         "The study validates itself: a wrong body force collapses the observed\n",
         "convergence rates. The cell prints them against theory and a verdict.\n"]),
    "Round6_PI_OneCycle.ipynb": (
        "cell_pi_onecycle.py",
        ["# The missing cell of the point-7b 2×2 — round 5, point 7b\n",
         "\n",
         "Three of the four boxes are measured:\n",
         "\n",
         "| | Adam 2e-3 | AdamW+OneCycle |\n",
         "|---|---|---|\n",
         "| physics-informed | **0.0959** | ← **this run** |\n",
         "| data-driven | 0.1307 | 0.0826 |\n",
         "\n",
         "Read the first column and the physics-informed loss wins by 36%.\n",
         "Read the diagonal and the data-driven one wins by 16%. They\n",
         "disagree because the diagonal changes the **optimizer and the loss\n",
         "at the same time** — the confound this project keeps hitting. Until\n",
         "the empty box is filled the two training *principles* cannot be\n",
         "ranked at all.\n",
         "\n",
         "* **NEEDS A GPU.** ~48 min, the same budget as the other three.\n",
         "* The recipe is copied exactly from the data-driven run: AdamW\n",
         "  lr=1e-3, wd=1e-5, OneCycleLR, 75,000 steps. Early stopping is off\n",
         "  on purpose — OneCycleLR converges in its final phase, so stopping\n",
         "  early would measure a truncated recipe.\n",
         "* The cell prints the finished 2×2 and says which reading holds.\n"]),
    "Round6_MMS_Operator.ipynb": (
        "cell_mms_operator.py",
        ["# MMS, the operator third — completes point 9's three-way\n",
         "\n",
         "Run **Round6_MMS.ipynb** first (Q4 and Q9). This trains the\n",
         "physics-informed operator on the same manufactured family and scores\n",
         "it with the **same error routine**, so all three are comparable.\n",
         "\n",
         "**Read before interpreting**: the operator minimizes the *same*\n",
         "discrete functional over the *same* Q4 space as the Q4 solver, and\n",
         "the minimizer of that functional **is** the Q4 solution. So the\n",
         "operator cannot beat Q4 here — that is arithmetic, not a finding.\n",
         "The number that means something is **operator / Q4**: 1.0 would mean\n",
         "the network has fully solved the variational problem. Below 1.0 means\n",
         "something is broken, and the cell says so.\n",
         "\n",
         "* **GPU preferred**; FP32, so T4/L4 are fine.\n",
         "* **~20–40 min** at N=17.\n",
         "* The cell **verifies the energy functional first** — the Q4 solution\n",
         "  must be the exact minimizer of the Π the network will minimize.\n",
         "* Labels are free (u\\* is analytic) but are **not used in training**;\n",
         "  the loss is the energy. They are only the scoring truth.\n"]),
    "Round6_OOD_Mitigation.ipynb": (
        "cell_ood_mitigation.py",
        ["# Does normalization fix the OOD degradation? — round 6, point 1b\n",
         "\n",
         "Timon: *\"If this diagnosis suggests a relatively straightforward\n",
         "mitigation, such as changing the training range or normalization, it\n",
         "would be useful to test it.\"* Section 8.6 named exactly that. This\n",
         "**tests** it instead of proposing it.\n",
         "\n",
         "* **GPU** for stage 1 (retraining). Any GPU — this is FP32 training,\n",
         "  not the FP64 solver sweep, so T4/L4 are fine.\n",
         "* **Stage 1 ~45–60 min**: retrain B1 × Neo-Hookean under the identical\n",
         "  protocol with `--normalize_inputs 1` as the only change.\n",
         "* **Stage 2 ~20–40 min**: re-run both OOD sweeps and compare. Fast\n",
         "  because the FEM references are **cached** — they do not depend on the\n",
         "  checkpoint, so the ~190 solves are reused, not repeated.\n",
         "* **Resumable** at both stages.\n",
         "\n",
         "A null result is a real result here. Standardizing is an affine\n",
         "rescaling, so a shifted E is still outside the trained range — if the\n",
         "curves barely move, that is the mechanism in §8.6 confirmed, and it is\n",
         "what gets reported.\n"]),
    "Round6_GPU_FEM_Sweep.ipynb": (
        "cell_gpu_fem_sweep.py",
        ["# GPU-native FEM scaling sweep + cost breakdown\n",
         "\n",
         "Timon round 5 point 8, extended by round 6: smaller intermediate sizes\n",
         "and an assembly-versus-solver cost breakdown.\n",
         "\n",
         "* **NEEDS A GPU** — Runtime → Change runtime type → T4/A100.\n",
         "  The cell stops with a clear message if there is none.\n",
         "* 0.02M → 3.93M DOF over eight resolutions. The four small ones take\n",
         "  minutes between them; the last two are hours each.\n",
         "* **Resumable**: each resolution is appended to the JSON as it\n",
         "  finishes, and each solve checkpoints internally.\n"]),
    "Round6_TorchFEM_Convergence_vs_Fine_Reference.ipynb": (
        "cell_torchfem_convergence_vs_fine_reference.py",
        ["# torch-fem accuracy + mesh convergence vs. the fine reference "
         "(round-9, items 2+6)\n",
         "\n",
         "Timon's reply to the standalone torch-fem question was explicit: "
         "\"timing should only be compared after the methods demonstrate\n",
         "comparable accuracy and mesh convergence,\" plus \"did you compare "
         "the accuracy of your FEM implementation with torch-FEM?\" The\n",
         "existing correctness check only ever ran at N=11 with a loose "
         "float32 tolerance — not a real answer to either question.\n",
         "\n",
         "**Methodology**: instead of a simpler ours-vs-torchfem pointwise "
         "diff, this runs torch-fem through the SAME study \"ours\" own\n",
         "Table 6a/6b/6c already uses — evaluated against the same fine "
         "~10M-DOF reference, via exact FE point location, with a fitted\n",
         "convergence rate across several N. Answers accuracy AND "
         "convergence together, directly comparable to \"ours\" own\n",
         "already-published L2/H1 numbers at the same N (this cell prints "
         "both side by side; \"ours\" needs no re-solve).\n",
         "\n",
         "**Prerequisite already applied**: torch-fem now runs at matched "
         "FP64/1e-8 (not the old float32/1e-3) — see torchfem_comparison.\n",
         "py's own docstring for the real bug this fixed.\n",
         "\n",
         "* **NEEDS A GPU** for a memory number comparable to \"ours,\" but "
         "runs on CPU too (just no peak-memory figure).\n",
         "* Deliberately stops at N=701 this run (~19-20GB expected at "
         "float64, roughly double torch-fem's own float32 9.7GB at this\n",
         "  N) rather than also attempting N=1001/1401 (38.1GB at float32, "
         "could approach ~76GB at float64) in the same run — a separate\n",
         "  follow-up should attempt those once this run's own N=701 memory "
         "usage is known.\n",
         "* **Resumable**: the fine ~10M-DOF reference RESUMES from \"ours\" "
         "own already-converged checkpoint (near-instant) rather than\n",
         "  re-solving it; each test resolution is appended to the JSON as "
         "it finishes.\n"]),
    "Round6_TorchFEM_Convergence_Extend_N1001_1401.ipynb": (
        "cell_torchfem_convergence_extend_N1001_1401.py",
        ["# Extend torch-fem convergence study to N=1001/1401\n",
         "\n",
         "Follow-up to Round6_TorchFEM_Convergence_vs_Fine_Reference.ipynb, "
         "now that N=701's real float64 peak memory is known (17.7GB,\n",
         "~1.83x the old float32 number) and this session's GPU turned out "
         "to be an 80GB A100 — projected ~34GB at N=1001 and ~67GB at\n",
         "N=1401, comfortable headroom on this GPU rather than the small-"
         "GPU risk the first notebook was deliberately conservative about.\n",
         "\n",
         "**Real result so far (N=51-701)**: torch-fem's own L2_rel/"
         "H1_semi_rel against the shared fine ~10M-DOF reference are\n",
         "IDENTICAL (every printed digit) to \"ours\" own already-published "
         "numbers at every N — both solvers converge to the SAME\n",
         "discretized FE solution, the strongest possible answer to "
         "Timon's accuracy question.\n",
         "\n",
         "* Same out_json as the first notebook — resumable, skips "
         "N=51-701 (already done), solves only N=1001 and N=1401.\n",
         "* **NEEDS A GPU** with enough memory (an 80GB A100 or similar) "
         "for the projected ~67GB at N=1401 — if a smaller GPU got\n",
         "  allocated this session, run only N=1001 and stop.\n"]),
    "Round6_TorchFEM_Timing_Breakdown.ipynb": (
        "cell_torchfem_timing_breakdown.py",
        ["# torch-fem timing breakdown by phase (round-9, item 3)\n",
         "\n",
         "Timon asked to \"report total time together with assembly, "
         "solve/factorization, nonlinear iterations and peak memory\" —\n",
         "the existing comparison only ever reported one aggregate "
         "wall-clock number per side.\n",
         "\n",
         "**How**: `solve_theirs_with_breakdown` instruments torch-fem's "
         "own Newton loop from the outside (no source changes) —\n",
         "monkeypatches `assemble_matrix`/`integrate_material` (assembly) "
         "and the module-level `sparse_solve` (linear solve) with\n",
         "timers for the duration of one solve call, restored after. "
         "Runs both \"cg\" (matched to the main study) and \"direct\"\n",
         "(a real factorization, Timon's own suggestion) — direct is "
         "tried only up to N=701 given the untested fill-in cost at\n",
         "larger DOF.\n",
         "\n",
         "**\"Ours\" side needs no new work**: nonlinear/CG iteration "
         "counts already live in highdof_stress_qoi_results/*.json,\n",
         "and it has no separate assembly phase by architecture — the "
         "cell's own printed analysis says so explicitly.\n",
         "\n",
         "* Produces a 3-panel figure (assembly vs. solve time, CG vs. "
         "direct, peak memory) saved to Drive, plus a printed\n",
         "  breakdown analysis for each resolution.\n",
         "* **Resumable**: skips (N, method) pairs already in its own "
         "out_json.\n",
         "* Runs on CPU too (slower, no peak-memory figure).\n"]),
    "Round6_TorchFEM_All_QoIs_Large_DOF.ipynb": (
        "cell_torchfem_all_qois_large_dof.py",
        ["# torch-fem vs. ours: all QoIs at large DOF (round-9, item 9)\n",
         "\n",
         "Timon: \"What about all QoIs, particularly for large DOFs (in "
         "the range of millions)?\" — the earlier convergence study\n",
         "only compared L2/H1 displacement error.\n",
         "\n",
         "**How**: extends the same fine-~10M-DOF-reference methodology "
         "with the energy norm and peak-stress QoIs already computed\n",
         "for \"ours\" own Table 6a-adjacent work "
         "(compute_tangent_energy_error, find_fine_peak_stress/\n",
         "compute_peak_stress_error) — torch-fem's numbers land in the "
         "same units/convention as \"ours\" already-published ones.\n",
         "\"Ours\" needs no new computation — its numbers already exist "
         "in highdof_stress_qoi_results/..._mgv_N701_1001_1401.json.\n",
         "\n",
         "* Targets N=1001 and N=1401 specifically — Timon's own "
         "\"large DOFs\" phrasing; L2/H1 at smaller N is already fully\n",
         "  covered by the earlier convergence study.\n",
         "* Produces a 3-panel figure (L2, energy-norm, peak-stress, "
         "ours vs. torch-fem, log scale) plus a printed per-N ratio\n",
         "  analysis across every QoI, not just the ones already "
         "reported.\n",
         "* **Resumable**: skips resolutions already in its own "
         "out_json.\n"]),
    "Round6_TorchFEM_Reaction_PK1_Components.ipynb": (
        "cell_torchfem_qoi_reaction_pk1_components.py",
        ["# Reaction force + per-component PK1 stress, ours vs. torch-fem (large DOF)\n",
         "\n",
         "Closes a real gap Omar flagged after re-reading the Summary himself: the "
         "earlier \"all QoIs at large DOF\" result (task #9) covered L2, H1,\n",
         "energy norm, and peak (Frobenius) stress — NOT reaction force or the "
         "per-component PK1 stress tensor (P11/P12/P21/P22), both established\n",
         "QoIs this project already tracks at the standard resolution. Calling "
         "the earlier result \"all QoIs\" was an overclaim until this ran.\n",
         "\n",
         "**How**: two new library functions in high_dof_convergence_study.py "
         "(pk1_component_errors_at_point, compute_reaction_resultant_error),\n",
         "smoke-tested locally at N=11 first. \"Ours\" side RESUMES from the "
         "existing coarse_*_N1001/1401.pt checkpoints already on Drive — no\n",
         "new multi-hour solve, just the new QoI computation on an "
         "already-solved field. torch-fem side resolves fresh (cheap, ~2-3\n",
         "minutes total).\n",
         "\n",
         "* Targets N=1001 and N=1401, matching task #9.\n",
         "* Produces a 2-panel figure (reaction-resultant relative error; "
         "per-component PK1 stress field error at N=1401) plus a printed\n",
         "  per-N, per-component ratio analysis.\n",
         "* Separate out_json files from task #9's own run — its "
         "resumability keys on N alone, so reusing the same file would\n",
         "  silently keep the old rows that lack these new fields.\n"]),
    "Round6_TensorMesh_Convergence_Production.ipynb": (
        "cell_tensormesh_convergence_production.py",
        ["# TensorMesh production-scale convergence (N=401-1401), sparse jac_fn\n",
         "\n",
         "Per Omar's explicit instruction (\"صلح تينسور وخلينا نكملها كما هو مطلوب\" — "
         "fix TensorMesh and let's finish it as required): the default\n",
         "dense-then-sparsify Jacobian in TensorMesh's own nonlinear_solve was "
         "measured to be intractable past N=51 (~10 days projected for N=401).\n",
         "\n",
         "**The fix**: an explicit sparse jac_fn (tensormesh_comparison.py's "
         "build_sparse_jac_fn), reusing this project's OWN already-correct,\n",
         "already-fast per-element Hessian machinery (matrix_free_solver.py's "
         "vmap+hessian local tangent) rather than re-deriving assembly from\n",
         "scratch. Real, measured result on CPU alone, before this notebook "
         "ever ran: N=51 dropped from 105.27s (dense) to 0.42-0.49s (sparse) —\n",
         "same accuracy (relative displacement-field difference 1.212e-11, "
         "unchanged). N=401 (torch-fem's own smallest production point)\n",
         "solved in 62.77s on CPU alone, previously projected at ~10 days.\n",
         "\n",
         "* Targets N=401/701/1001/1401, matching torch-fem's own sweep "
         "exactly, against the same fine ~10M-DOF reference.\n",
         "* Produces a 2-panel figure (L2 error; wall-clock time, both "
         "TensorMesh vs. torch-fem) plus a printed per-N analysis.\n",
         "* Watch for a jump in TensorMesh's own wall-clock between N=701 "
         "and N=1001 — that would be torch_sla's own\n",
         "  CUDA_ITERATIVE_THRESHOLD (2,000,000 DOF) switching the direct "
         "solver to an iterative fallback, not a regression.\n",
         "* **Resumable**: skips resolutions already in its own out_json.\n"]),
    "Round6_NO_Inference_vs_TorchFEM_N1401.ipynb": (
        "cell_no_inference_vs_torchfem_N1401.py",
        ["# NO inference time vs. torch-fem at N=1401 (round-9, item 12)\n",
         "\n",
         "Timon: \"Did you try for N=1401 NO inference time and compare "
         "it to the 30s of torch-FEM?\" — not previously measured: the\n",
         "operator's own Table 7 latency number was measured at the "
         "study's standard resolution (N=21), not N=1401.\n",
         "\n",
         "**How**: `build_sample_b1(N=1401, seed=0, material="
         "'neo_hookean', solve_fem=False)` builds the mesh/BC/material\n",
         "structure at N=1401 WITHOUT solving the FEM ground truth "
         "(hours at this size, not needed for a timing measurement),\n",
         "fed into `benchmark_inference_latency_Q4` — the exact same "
         "timing protocol that produced Table 7's own number.\n",
         "\n",
         "Compares against BOTH torch-fem N=1401 numbers now on record: "
         "133.83s (matched FP64/1e-8, this project's own real\n",
         "number) and 29.1s (\"~30s\", the old unmatched float32/1e-3 "
         "number Timon's email likely refers to).\n",
         "\n",
         "* **NEEDS A GPU** for a number comparable to Table 7's own "
         "GPU-measured figure.\n",
         "* **Real, stated risk**: N=1401 is far beyond any resolution "
         "this operator has ever been evaluated at (zero-shot study:\n",
         "  up to N=49 only) — this measures whatever actually happens "
         "at that scale (fast, slow, or an OOM), not an assumption.\n",
         "* Checkpoint path is guessed (`CKPT` near the top of the "
         "cell) — update it if the assert fails.\n",
         "* Produces a bar-chart figure (log scale) plus a printed "
         "speedup analysis, with the accuracy caveat stated explicitly\n",
         "  (fast inference here is not evidence of accuracy at a mesh "
         "size never validated).\n"]),
    "Round6_TorchFEM_Tolerance_Sensitivity.ipynb": (
        "cell_torchfem_tolerance_sensitivity.py",
        ["# torch-fem tolerance sensitivity: 1e-6/1e-7 vs. 1e-8 "
         "(round-9, optional item)\n",
         "\n",
         "Timon's own suggestion, explicitly optional: \"If you wish "
         "you can also test 10^-6 or 10^-7 and report the difference\"\n",
         "— unlike the FP64/1e-8 request itself (\"we certainly "
         "should\"), which is already done.\n",
         "\n",
         "**How**: reruns `run_convergence_study` at N=401 and N=1401 "
         "(small and large ends of the already-measured range) at\n",
         "tol=1e-6 and tol=1e-7, each to its OWN out_json file "
         "(resumability keys on N alone, not (N, tol), so sharing one\n",
         "file across tolerances at the same N would silently skip the "
         "second run) — reuses the already-committed tol=1e-8 numbers\n",
         "rather than re-solving them.\n",
         "\n",
         "* Produces a 2-panel figure (accuracy + wall-clock vs. "
         "tolerance, one panel per N) plus a printed analysis of\n",
         "  whether loosening the tolerance actually saves meaningful "
         "time for the accuracy given up.\n",
         "* Cheap: at most 4 new torch-fem solves (2 tolerances x 2 "
         "resolutions), each a few seconds to ~2 minutes.\n"]),
}


def build(nb_name, py_name, md_lines):
    with open(os.path.join(HERE, py_name)) as f:
        code = f.read()
    # splitlines(keepends=True) preserves every "\n"; the last line may lack
    # one, which is the only place nbformat allows it.
    src = code.splitlines(keepends=True)
    nb = {
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": md_lines},
            {"cell_type": "code", "execution_count": None, "metadata": {},
             "outputs": [], "source": src},
        ],
        "metadata": {
            "accelerator": "GPU" if "GPU_FEM" in nb_name else "None",
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4, "nbformat_minor": 0,
    }
    path = os.path.join(HERE, nb_name)
    with open(path, "w") as f:
        json.dump(nb, f, indent=1)
    print(f"wrote {nb_name}  ({len(src)} source lines)")
    return path


if __name__ == "__main__":
    for nb_name, (py_name, md) in NOTEBOOKS.items():
        build(nb_name, py_name, md)
    print()
    subprocess.run([sys.executable, os.path.join(HERE, "check_notebooks.py")],
                   check=True)
