"""Wraps the two round-6 cells into real .ipynb notebooks.

The .py files are meant to be pasted into a Colab cell. Handing them to
Colab as files makes it try to parse them as notebook JSON, which fails with
`Unexpected token '#'`. These are actual notebooks, so a Colab link opens
them directly.

Every source line keeps its trailing newline -- nbformat stores a cell's
source as a list of lines and Jupyter concatenates it verbatim, so a missing
"\\n" glues lines together into a SyntaxError. That bug shipped once already;
check_notebooks.py exists to catch it and is run at the end of this script.
"""
import os
import json
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

NOTEBOOKS = {
    "Round6_B2_Retrain.ipynb": (
        "cell_b2_retrain_and_eval.py",
        ["# B2 zero-shot: retrain on the repaired data, then re-evaluate\n",
         "\n",
         "All three B2 cases produced relative errors of **8 to 14.5** — 800% to\n",
         "1450%, against 5.0-10.6% for the three B1 cases — and nearly flat in the\n",
         "mesh. Their cached load had been overstated by a factor that **depended\n",
         "on the mesh**, about 13x at N=21 against 21x at N=33, which for a study\n",
         "that measures transfer across meshes invalidates them outright.\n",
         "\n",
         "The caches are repaired and checked. The models fitted to the bad load\n",
         "are gone. This notebook does the half that was never done: **retrain,\n",
         "then re-evaluate**.\n",
         "\n",
         "* **NEEDS A GPU.** ~45 min per case to train on an A100.\n",
         "* **The eval is cheap** — the twenty N=101 references per case are\n",
         "  cached and were never touched by the load bug, so the eight hours the\n",
         "  B1 evals took do not recur. The cell prints the cached count per case\n",
         "  before starting, so the real cost is visible up front.\n",
         "* **Resumable** at every stage.\n",
         "\n",
         "**It carries one hard-won correction.** Report section 9.1 established\n",
         "that once B2's boundary force is FEM-consistent, correcting it *alone*\n",
         "makes accuracy **worse** — 32.46% to 94.08% — because the smaller,\n",
         "correct force weakens the only gradient pulling the network off the\n",
         "all-zero solution. `train_B2.py` fixes that with `--loss_force_norm`,\n",
         "on by default. The zero-shot trainer had no such option, and the first\n",
         "retrain attempt was reproducing that exact regression (combined val\n",
         "error 0.96 at epoch 25, 1.13 at epoch 50) before it was stopped. The\n",
         "option is now ported, its default resolved from the geometry, and\n",
         "printed at the top of every run.\n",
         "\n",
         "So the first thing to look for in the output is:\n",
         "\n",
         "```\n",
         "[loss_force_norm] not given; resolved to 1 from geometry B2.\n",
         "```\n",
         "\n",
         "If that line is missing, the code did not update — stop and say so.\n"]),
    "Round6_Pareto_B1.ipynb": (
        "cell_pareto_remaining_B1.py",
        ["# Accuracy/cost Pareto — the two remaining B1 cases\n",
         "\n",
         "Round-5 point 2, already done for B1 x Neo-Hookean (report Table 18).\n",
         "This runs the same study for **Mooney-Rivlin** and **Arruda-Boyce**,\n",
         "whose zero-shot checkpoints are valid, so the Pareto can be stated on\n",
         "three materials instead of one.\n",
         "\n",
         "* **NEEDS A GPU.**\n",
         "* **Budget ~2 h per case, and do not be surprised by three times that.**\n",
         "  The two B1 x Neo-Hookean runs took 1 h 54 m and 6 h 24 m for the SAME\n",
         "  configuration on different Colab runtimes. An earlier note in\n",
         "  PROJECT_STATUS said \"minutes\"; that was wrong.\n",
         "* **Resumable**: a case whose JSON already exists is skipped.\n",
         "\n",
         "Why it costs that much: the Pareto draws its own problem instances\n",
         "(seeds 900_000 + i) and needs one fine FEM solve at N=101 per sample as\n",
         "the shared reference. Those are not the zero-shot study's references —\n",
         "different seeds, different problems — so they cannot be borrowed.\n",
         "\n",
         "Both checkpoints are checked before either case starts, so a missing\n",
         "one costs a second rather than two hours. Independent of the B2 retrain\n",
         "and the CG check; all three can run at the same time on separate\n",
         "runtimes.\n"]),
    "Round6_MMS_Operator_Rate.ipynb": (
        "cell_mms_operator_rate.py",
        ["# Does the MMS operator have a convergence rate of its own?\n",
         "\n",
         "**Optional, and cheap.** Section 8.11 names this as a limitation in\n",
         "its own words: *\"The operator was trained and scored at one mesh only,\n",
         "so it has no convergence rate of its own and cannot appear in Table 23;\n",
         "producing one means a training run per refinement, not a solve per\n",
         "refinement.\"*\n",
         "\n",
         "This does those training runs. N=17 is already measured; adding **N=9\n",
         "and N=33** gives three points, the same number Table 23 fits Q4 and Q9\n",
         "on.\n",
         "\n",
         "* **~1 hour**, and bounded — nothing here can run away.\n",
         "* GPU preferred; the FEM references are FP64 on CPU and at N=33 they\n",
         "  are the slower half.\n",
         "* **Resumable**: a resolution whose JSON exists is skipped.\n",
         "\n",
         "**A flat result is still a result.** Unlike Q4 and Q9, the operator has\n",
         "no theoretical rate to be checked against, so whatever comes out is a\n",
         "measurement rather than a verification. If its error does not improve\n",
         "with the mesh, that is worth reporting plainly: an operator whose error\n",
         "ignores refinement is a different object from a discretization whose\n",
         "error does not.\n",
         "\n",
         "The Q4 rates are computed alongside as a **control** — they should land\n",
         "near Table 23's 1.98 and 1.00. If they do not, this run is not\n",
         "comparable to that table and the operator rates should not be quoted.\n"]),
    "Round6_B2_BatchSize_Diagnostic.ipynb": (
        "cell_b2_batchsize_diagnostic.py",
        ["# Why will B2 zero-shot not train?\n",
         "\n",
         "`loss_force_norm` was necessary and **is not sufficient**. With it on,\n",
         "all three B2 cases still peaked at their FIRST validation and got worse\n",
         "from there — best combined val 0.9986, 0.9752, 1.0267 — and evaluated\n",
         "at 0.87-0.89, flat in the mesh to the fourth decimal. That is a model\n",
         "that never learned.\n",
         "\n",
         "**The candidate**: `b2_accuracy_search.py`'s `lossnorm` trial reached\n",
         "9.11% on this exact case, and it calls `train_B2.py` without\n",
         "`--batch_size`, i.e. at that script's default of **1**. The zero-shot\n",
         "trainer defaults to **8**. B1 is unaffected — it uses 8 on both sides\n",
         "and trains fine.\n",
         "\n",
         "**This is a candidate, not a diagnosis.** The last candidate did not\n",
         "hold, so this cell tests it: two arms on one case at **matched\n",
         "optimizer steps**, batch 8 against batch 1. Equal steps and not equal\n",
         "epochs, because at batch 1 an epoch is 800 steps rather than 100 and\n",
         "equal epochs would hand one arm eight times the training.\n",
         "\n",
         "* **~15-20 min** on an A100.\n",
         "* Early stopping is off in both arms, so each runs its full budget.\n",
         "* Neither arm writes to the real case directory.\n",
         "\n",
         "It prints one of three verdicts, including the one where batch size is\n",
         "**not** the cause — in which case it names the next candidates rather\n",
         "than leaving you to guess.\n"]),
    "Round6_B2_InputNorm.ipynb": (
        "cell_b2_input_norm.py",
        ["# Does standardising the input channels fix B2 zero-shot?\n",
         "\n",
         "The B1 control arm did its job. Same trainer, same protocol, B1\n",
         "reaches 0.066 and B2 sits at ~1.0, and the probe says how they differ:\n",
         "\n",
         "| | B1 | B2 |\n",
         "|---|---|---|\n",
         "| descent captured | **100%** | **47%** (37-60%) |\n",
         "| correlation | +0.997..+0.9996 | +0.87 down to **-0.11** |\n",
         "| amplitude ratio | 0.98-1.02 | **0.23-0.61** |\n",
         "| roughness | **1.01x** | **3.00x** |\n",
         "| rms(f)/rms(E) fed in | 6.1e-4 - 8.2e-4 | **2.3e-5 - 7.2e-5** |\n",
         "\n",
         "Roughness is `(U ratio)/(amplitude ratio)^2` -- 1.0 for a field as\n",
         "smooth as the truth. B2 carries **three times** the strain energy its\n",
         "size warrants: its field is **rough, not merely small**, so rescaling\n",
         "cannot fix it, and the `Pi(s*pred)` scan agrees (s = 1.0 on six of\n",
         "eight).\n",
         "\n",
         "**The one candidate the control singles out** is the input channels:\n",
         "the two carrying the load are **10-30x quieter** relative to stiffness\n",
         "on B2 than on B1, and nonzero on 3-5% of nodes. On top of that B2\'s\n",
         "per-node load scale changes **1.98x** between its two training meshes\n",
         "while the total is constant to 0.001% -- same physics, two numbers.\n",
         "\n",
         "**This is not the difference between the arms** -- neither run used any\n",
         "normalisation. It is a candidate *remedy* for a condition that is much\n",
         "worse on B2, and it may not work. **If the normalised run also lands\n",
         "near 1.0, the input scaling is not the obstacle** and the next place to\n",
         "look is the Dirichlet ramp or the parametric family.\n",
         "\n",
         "**Needs a GPU, ~15 min, one arm. Nothing touches the real run.**\n"]),
    "Round6_B2_Model_Probe.ipynb": (
        "cell_b2_model_probe.py",
        ["# What is the trained B2 model doing, and what is it fed?\n",
         "\n",
         "The functional check settled the previous question. Pi(s * uv_exact)\n",
         "was scanned over s on six samples at both training resolutions and the\n",
         "minimum landed at **s = 1.000 every time**, with |W|/U = 2.00 to three\n",
         "decimals. The cache is fine, the work term is fine, and the functional\n",
         "the trainer minimises really is minimised by the FEM solution.\n",
         "\n",
         "That rules out the data and leaves the training path. This looks at\n",
         "the path directly, with the checkpoint already on Drive.\n",
         "\n",
         "The first run returned real information **and** showed that two things\n",
         "in the probe itself were built wrong. Both are fixed here:\n",
         "\n",
         "* it printed `Pi(pred)` with no `Pi(uv_exact)` **for the same sample** --\n",
         "  the functional test reads `train_samples`, this reads `val_samples`,\n",
         "  and those are different problems, so the number could not be compared\n",
         "  with anything. Both are computed here now, per sample.\n",
         "* it put the channel scales at N=21 and N=33 side by side as if the\n",
         "  difference were a **mesh** effect. The cache seeds each resolution\n",
         "  differently, so those are different **draws** too. One fixed seed is\n",
         "  now rebuilt on both meshes, which is the controlled version.\n",
         "\n",
         "**And it adds the control that was missing.** B1 reaches 0.066 on the\n",
         "same trainer and protocol, so any account of B2\'s failure that applies\n",
         "equally to B1 explains nothing. Both arms run, printed for comparison.\n",
         "\n",
         "What the first run established: the model is **not** predicting zero,\n",
         "its amplitude is 2.5-4x too small, `W/U ~ 2` so **rescaling would not\n",
         "help**, `U(pred)` is nearly constant across every sample and both meshes\n",
         "while the targets span 3x, and it responds to its input about **five\n",
         "times too weakly**.\n",
         "\n",
         "**CPU, a couple of minutes, writes nothing, trains nothing.**\n"]),
    "Round6_B2_Functional_Check.ipynb": (
        "cell_b2_functional_check.py",
        ["# Is the cached FEM solution a minimum of the trainer's Pi?\n",
         "\n",
         "Two candidates tested, neither explains the B2 failure:\n",
         "`loss_force_norm` (necessary, not sufficient) and batch size\n",
         "(0.9888 against 0.9444 at matched steps — noise on curves swinging\n",
         "0.94 to 1.45).\n",
         "\n",
         "**The clue nobody used**: a relative error of 1.0 is not an arbitrary\n",
         "bad number. The metric is `0.5*(rms(e_u)/rms(u) + rms(e_v)/rms(v))`,\n",
         "and substituting `uv_pred = 0` gives exactly 1. All three B2 runs sat\n",
         "at 0.94–1.23. So the network is probably predicting nothing — and it\n",
         "may be doing so **correctly**, because a network that minimizes Pi\n",
         "goes wherever Pi's minimum is.\n",
         "\n",
         "That turns the question away from the optimizer entirely: is Pi's\n",
         "minimum, built from this cache's `node_forces`, anywhere near this\n",
         "cache's `uv_exact`? **No training needed to answer it.**\n",
         "\n",
         "It scans `Pi(s * uv_exact)` for s from 0 to 1.5. The true solution\n",
         "should win at s=1. If the minimum sits near s=0 the work term is too\n",
         "weak, the trainer is correctly finding zero, and **no optimizer\n",
         "setting will help** — the fault is in the data.\n",
         "\n",
         "* **Seconds. No GPU. Reads the cache, writes nothing.**\n",
         "* It asserts its stand-in field really does reproduce `uv_exact`\n",
         "  through the soft-Dirichlet ramp *before* reporting anything, so a\n",
         "  wrong assumption about the mask cannot pass itself off as physics.\n",
         "  If it stops on that assertion, that is the finding.\n"]),
    "Round6_Check_Results.ipynb": (
        "cell_check_results.py",
        ["# What is actually on Drive?\n",
         "\n",
         "Read-only. Shows which results exist and how far each got, so a run\n",
         "that printed nothing can be told apart from one that did nothing.\n",
         "Safe to run at any time, including while other notebooks are working.\n"]),
    "Round6_OOD_Progressive.ipynb": (
        "cell_ood_progressive.py",
        ["# Progressive OOD shift — Timon round 6, point 1\n",
         "\n",
         "Separates **material stiffness** from **loading** and sweeps the shift\n",
         "from 0 to 3σ, instead of the single 2–2.5σ pair Table 11 measured.\n",
         "\n",
         "* **CPU is fine** — no GPU needed.\n",
         "* **~1.5–4 h** for the full 19-cell grid at 10 samples each.\n",
         "* **Resumable**: every cell is written to Drive as it finishes and\n",
         "  skipped on a re-run. After a disconnect, just run the cell again.\n",
         "\n",
         "Edit `GEOMETRY`, `MATERIAL` and `CKPT` in the cell to pick the case.\n"]),
    "Round6_Data_Driven.ipynb": (
        "cell_data_driven.py",
        ["# Data-driven operator — Timon round 5, point 7b\n",
         "\n",
         "The same Transolver, same mesh, same 800/200 split, same optimizer and\n",
         "the **same optimizer-step budget** — trained on FEM solutions instead of\n",
         "the energy functional. Only the loss differs, so the comparison isolates\n",
         "the training principle rather than the architecture.\n",
         "\n",
         "* **No new FEM solves** — the labels are already in the dataset.\n",
         "* **GPU strongly preferred**; CPU works but will be slow.\n",
         "* Expected to finish inside the physics-informed run's 48 minutes,\n",
         "  since a data loss skips the per-step energy assembly.\n",
         "\n",
         "The script also reports the **label-generation cost** the data-driven\n",
         "model implicitly requires and the physics-informed one does not — about\n",
         "5.7 h of CPU for 800 B1 × Neo-Hookean solves at Table 4a's measured rate.\n"]),
    "Round6_MMS.ipynb": (
        "cell_mms.py",
        ["# Method of manufactured solutions — round 5, point 9 (FEM half)\n",
         "\n",
         "Timon: *\"compare Q4, Q9 and the physics-informed Transolver against\n",
         "exactly the same analytical solution in L2, H1 and energy norms and\n",
         "also examine stress errors\"*, and *\"this is the last thing to do\"*.\n",
         "\n",
         "**This notebook is the FEM half: Q4 and Q9.** The operator half needs\n",
         "a body-force term in the energy functional and a body-force input\n",
         "channel — a separate piece of work, described in `mms_study.py`.\n",
         "\n",
         "**The fork Timon left open is resolved here as body force**, because a\n",
         "body-force-free exact solution on this geometry is a homogeneous\n",
         "deformation, which Q4 reproduces to machine precision — the study\n",
         "would measure round-off and distinguish nothing.\n",
         "\n",
         "* **GPU optional.** FP64, so a T4/L4 buys little; `--cpu` is fine.\n",
         "* **Minutes** for N up to 33.\n",
         "* **Resumable**: each (order, N) row is appended as it finishes.\n",
         "\n",
         "The study validates itself: a wrong body force collapses the observed\n",
         "convergence rates. The cell prints them against theory and a verdict.\n"]),
    "Round6_PI_OneCycle.ipynb": (
        "cell_pi_onecycle.py",
        ["# The missing cell of the point-7b 2×2 — round 5, point 7b\n",
         "\n",
         "Three of the four boxes are measured:\n",
         "\n",
         "| | Adam 2e-3 | AdamW+OneCycle |\n",
         "|---|---|---|\n",
         "| physics-informed | **0.0959** | ← **this run** |\n",
         "| data-driven | 0.1307 | 0.0826 |\n",
         "\n",
         "Read the first column and the physics-informed loss wins by 36%.\n",
         "Read the diagonal and the data-driven one wins by 16%. They\n",
         "disagree because the diagonal changes the **optimizer and the loss\n",
         "at the same time** — the confound this project keeps hitting. Until\n",
         "the empty box is filled the two training *principles* cannot be\n",
         "ranked at all.\n",
         "\n",
         "* **NEEDS A GPU.** ~48 min, the same budget as the other three.\n",
         "* The recipe is copied exactly from the data-driven run: AdamW\n",
         "  lr=1e-3, wd=1e-5, OneCycleLR, 75,000 steps. Early stopping is off\n",
         "  on purpose — OneCycleLR converges in its final phase, so stopping\n",
         "  early would measure a truncated recipe.\n",
         "* The cell prints the finished 2×2 and says which reading holds.\n"]),
    "Round6_MMS_Operator.ipynb": (
        "cell_mms_operator.py",
        ["# MMS, the operator third — completes point 9's three-way\n",
         "\n",
         "Run **Round6_MMS.ipynb** first (Q4 and Q9). This trains the\n",
         "physics-informed operator on the same manufactured family and scores\n",
         "it with the **same error routine**, so all three are comparable.\n",
         "\n",
         "**Read before interpreting**: the operator minimizes the *same*\n",
         "discrete functional over the *same* Q4 space as the Q4 solver, and\n",
         "the minimizer of that functional **is** the Q4 solution. So the\n",
         "operator cannot beat Q4 here — that is arithmetic, not a finding.\n",
         "The number that means something is **operator / Q4**: 1.0 would mean\n",
         "the network has fully solved the variational problem. Below 1.0 means\n",
         "something is broken, and the cell says so.\n",
         "\n",
         "* **GPU preferred**; FP32, so T4/L4 are fine.\n",
         "* **~20–40 min** at N=17.\n",
         "* The cell **verifies the energy functional first** — the Q4 solution\n",
         "  must be the exact minimizer of the Π the network will minimize.\n",
         "* Labels are free (u\\* is analytic) but are **not used in training**;\n",
         "  the loss is the energy. They are only the scoring truth.\n"]),
    "Round6_OOD_Mitigation.ipynb": (
        "cell_ood_mitigation.py",
        ["# Does normalization fix the OOD degradation? — round 6, point 1b\n",
         "\n",
         "Timon: *\"If this diagnosis suggests a relatively straightforward\n",
         "mitigation, such as changing the training range or normalization, it\n",
         "would be useful to test it.\"* Section 8.6 named exactly that. This\n",
         "**tests** it instead of proposing it.\n",
         "\n",
         "* **GPU** for stage 1 (retraining). Any GPU — this is FP32 training,\n",
         "  not the FP64 solver sweep, so T4/L4 are fine.\n",
         "* **Stage 1 ~45–60 min**: retrain B1 × Neo-Hookean under the identical\n",
         "  protocol with `--normalize_inputs 1` as the only change.\n",
         "* **Stage 2 ~20–40 min**: re-run both OOD sweeps and compare. Fast\n",
         "  because the FEM references are **cached** — they do not depend on the\n",
         "  checkpoint, so the ~190 solves are reused, not repeated.\n",
         "* **Resumable** at both stages.\n",
         "\n",
         "A null result is a real result here. Standardizing is an affine\n",
         "rescaling, so a shifted E is still outside the trained range — if the\n",
         "curves barely move, that is the mechanism in §8.6 confirmed, and it is\n",
         "what gets reported.\n"]),
    "Round6_GPU_FEM_Sweep.ipynb": (
        "cell_gpu_fem_sweep.py",
        ["# GPU-native FEM scaling sweep + cost breakdown\n",
         "\n",
         "Timon round 5 point 8, extended by round 6: smaller intermediate sizes\n",
         "and an assembly-versus-solver cost breakdown.\n",
         "\n",
         "* **NEEDS A GPU** — Runtime → Change runtime type → T4/A100.\n",
         "  The cell stops with a clear message if there is none.\n",
         "* 0.02M → 3.93M DOF over eight resolutions. The four small ones take\n",
         "  minutes between them; the last two are hours each.\n",
         "* **Resumable**: each resolution is appended to the JSON as it\n",
         "  finishes, and each solve checkpoints internally.\n"]),
}


def build(nb_name, py_name, md_lines):
    with open(os.path.join(HERE, py_name)) as f:
        code = f.read()
    # splitlines(keepends=True) preserves every "\n"; the last line may lack
    # one, which is the only place nbformat allows it.
    src = code.splitlines(keepends=True)
    nb = {
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": md_lines},
            {"cell_type": "code", "execution_count": None, "metadata": {},
             "outputs": [], "source": src},
        ],
        "metadata": {
            "accelerator": "GPU" if "GPU_FEM" in nb_name else "None",
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4, "nbformat_minor": 0,
    }
    path = os.path.join(HERE, nb_name)
    with open(path, "w") as f:
        json.dump(nb, f, indent=1)
    print(f"wrote {nb_name}  ({len(src)} source lines)")
    return path


if __name__ == "__main__":
    for nb_name, (py_name, md) in NOTEBOOKS.items():
        build(nb_name, py_name, md)
    print()
    subprocess.run([sys.executable, os.path.join(HERE, "check_notebooks.py")],
                   check=True)
